import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { requireRole } from "@/lib/auth/session";
import { getFinanceSnapshot } from "@/lib/finance";
import { proposeFinanceExpenseAction, reviewFinanceExpenseAction, payFinanceExpenseAction, publishFinanceExpenseAction, proposeFinanceCorrectionAction, approveFinanceCorrectionAction } from "@/app/actions/finance";
import { AdminNav, ErrorNotice, StatusBadge } from "@/components/operations";

export const dynamic = "force-dynamic";
const money = (value: number) => `PKR ${value.toLocaleString("en-PK")}`;

export default async function AdminFinancePage({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  await requireRole(["ADMIN"]);
  const [{ error }, funds, campaigns, complaints, expenses, pendingDonations, audit, corrections] = await Promise.all([
    searchParams, getFinanceSnapshot(),
    prisma.donationCampaign.findMany({ where: { approvedAt: { not: null }, status: { in: ["PUBLISHED", "CLOSED"] } }, select: { id: true, title: true }, orderBy: { title: "asc" } }),
    prisma.complaint.findMany({ select: { id: true, reference: true, title: true }, orderBy: { createdAt: "desc" }, take: 100 }),
    prisma.donationExpense.findMany({ include: { campaign: { select: { title: true } }, complaint: { select: { reference: true } }, recordedBy: { select: { name: true } }, approvedBy: { select: { name: true } } }, orderBy: { createdAt: "desc" }, take: 100 }),
    prisma.donationIntent.count({ where: { status: "PENDING" } }),
    prisma.donationAudit.findMany({ where: { targetType: "DonationExpense" }, orderBy: { createdAt: "desc" }, take: 30, select: { id: true, action: true, createdAt: true, targetId: true, actor: { select: { name: true } } } }),
    prisma.financeCorrection.findMany({ orderBy: { createdAt: "desc" }, take: 50, include: { expense: { select: { purpose: true } }, proposedBy: { select: { name: true } }, approvedBy: { select: { name: true } } } }),
  ]);
  return <section className="inner-page"><div className="page-shell"><p className="section-kicker">Accountable community funding</p><h1 className="page-heading mt-3">Finance</h1><p className="page-subtitle">Review claimed transfers separately from spending. An expense affects the cash balance only after approval and a recorded payment date.</p><AdminNav /><ErrorNotice error={error} />
    <div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Verified receipts", funds.gross], ["Refunds", funds.refunds], ["Paid expenses", funds.spent], ["Available", funds.available]].map(([title, amount]) => <div className="surface-card" key={title}><p className="text-2xl font-bold">{money(Number(amount))}</p><p className="mt-2 text-sm text-slate-600">{title}</p></div>)}</div>{funds.negativeFunds.length > 0 && <p className="mt-4 rounded-xl bg-amber-50 p-4 text-sm text-amber-900">{funds.negativeFunds.length} allocation needs reconciliation. Negative balances are shown in the records.</p>}
    <div className="mt-6 flex flex-wrap gap-4 text-sm font-bold text-emerald-700"><Link href="/admin/finance/allocations" className="underline">Review city allocations</Link><Link href="/admin/donations" className="underline">Review {pendingDonations} pending payments</Link><Link href="/admin/donations/expenses" className="underline">Historical paid expenses</Link><Link href="/funds" className="underline">Public funds page</Link><Link href="/funds/report.csv" className="underline">Download public CSV</Link></div>
    <div className="mt-8 grid gap-7 xl:grid-cols-[380px_1fr]"><form action={proposeFinanceExpenseAction} className="surface-card h-fit space-y-4"><h2 className="text-xl font-bold">Propose an expense</h2><p className="text-sm text-slate-600">A proposal does not reduce available funds. Review, record payment, then publish a safe summary.</p><label className="block"><span className="field-label">Fund</span><select name="campaignId" className="field-input"><option value="">General fund</option>{campaigns.map(item => <option key={item.id} value={item.id}>{item.title}</option>)}</select></label><label className="block"><span className="field-label">Related complaint (optional)</span><select name="complaintId" className="field-input"><option value="">None</option>{complaints.map(item => <option key={item.id} value={item.id}>{item.reference} · {item.title.slice(0, 35)}</option>)}</select></label><label className="block"><span className="field-label">Amount (PKR)</span><input name="amount" type="number" min="100" max="1000000" className="field-input" required /></label><label className="block"><span className="field-label">Public-safe purpose</span><input name="purpose" minLength={5} maxLength={200} className="field-input" required /></label><label className="block"><span className="field-label">Documentation summary (no private contacts)</span><textarea name="documentation" minLength={10} maxLength={1000} className="field-input min-h-24" required /></label><label className="block"><span className="field-label">Private receipt image (optional, max 3 MB)</span><input name="receipt" type="file" accept="image/jpeg,image/png,image/webp" className="field-input" /></label><button className="btn-dark cursor-pointer" type="submit">Save proposal</button></form>
    <div className="space-y-4"><h2 className="text-xl font-bold">Expense review and payment</h2>{expenses.length ? expenses.map(item => <article className="surface-card" key={item.id}><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-bold">{item.purpose}</h3><p className="mt-1 text-xs text-slate-600">{item.campaign?.title ?? "General fund"} · {item.complaint ? <Link className="underline" href={`/admin/cases/${item.complaintId}`}>{item.complaint.reference}</Link> : "No linked case"} · by {item.recordedBy.name}</p></div><strong>{money(item.amountPkr)}</strong></div><div className="mt-2"><StatusBadge status={item.status} /></div><p className="mt-3 whitespace-pre-wrap text-sm text-slate-700">{item.documentation}</p>{item.receiptKey && <Link href={`/api/finance/receipts/${item.id}`} target="_blank" className="mt-2 inline-block text-sm font-bold text-emerald-700 underline">View private receipt</Link>}{item.approvedBy && <p className="mt-2 text-xs text-slate-600">Reviewed by {item.approvedBy.name}{item.approvedAt ? ` on ${item.approvedAt.toLocaleDateString("en-PK")}` : ""}</p>}{item.paidAt && <p className="mt-1 text-xs text-slate-600">Paid {item.paidAt.toLocaleDateString("en-PK")} · {item.publishedAt ? "Public summary published" : "Public summary pending"}</p>}
      {item.status === "DRAFT" && <div className="mt-4 flex flex-wrap gap-2"><form action={reviewFinanceExpenseAction}><input type="hidden" name="id" value={item.id} /><button name="decision" value="APPROVED" className="rounded-lg bg-emerald-700 px-4 py-2 text-sm font-bold text-white">Approve proposal</button></form><form action={reviewFinanceExpenseAction}><input type="hidden" name="id" value={item.id} /><button name="decision" value="CANCELLED" className="rounded-lg border px-4 py-2 text-sm font-bold">Cancel proposal</button></form></div>}
      {item.status === "APPROVED" && <form action={payFinanceExpenseAction} className="mt-4 flex flex-wrap items-end gap-3"><input type="hidden" name="id" value={item.id} /><label className="text-sm"><span className="field-label">Actual payment date</span><input type="date" name="paidAt" className="field-input" required /></label><button className="rounded-lg bg-emerald-700 px-4 py-3 text-sm font-bold text-white">Record payment</button></form>}
      {item.status === "PAID" && !item.publishedAt && <form action={publishFinanceExpenseAction} className="mt-4"><input type="hidden" name="id" value={item.id} /><button className="text-sm font-bold text-emerald-700 underline">Publish approved spending summary</button></form>}{item.status === "PAID" && <details className="mt-4 border-t pt-3"><summary className="cursor-pointer text-sm font-bold">Propose an audited correction</summary><form action={proposeFinanceCorrectionAction} className="mt-3 grid gap-3 sm:grid-cols-[140px_1fr_auto]"><input type="hidden" name="expenseId" value={item.id} /><label><span className="field-label">PKR change (+/−)</span><input name="deltaPkr" type="number" min="-1000000" max="1000000" className="field-input" required /></label><label><span className="field-label">Reason (public if expense published)</span><input name="reason" minLength={20} maxLength={500} className="field-input" required /></label><button className="self-end rounded-lg border px-4 py-3 text-sm font-bold">Propose</button></form></details>}</article>) : <p className="surface-card text-sm text-slate-600">No expenses recorded.</p>}</div></div>
    <section className="surface-card mt-8"><h2 className="text-xl font-bold">Correction review</h2><p className="mt-1 text-sm text-slate-600">Approved adjustments stay alongside the original expense and its audit trail.</p>{corrections.length ? <div className="mt-4 space-y-3">{corrections.map(item => <div key={item.id} className="rounded-lg border p-3 text-sm"><p><strong>{item.expense.purpose}</strong> · {item.deltaPkr > 0 ? "+" : ""}{money(item.deltaPkr)} spending adjustment</p><p className="mt-1 text-slate-600">{item.reason} · proposed by {item.proposedBy.name}{item.approvedBy ? ` · approved by ${item.approvedBy.name}` : ""}</p>{!item.approvedAt && <form action={approveFinanceCorrectionAction} className="mt-2"><input type="hidden" name="id" value={item.id} /><button className="font-bold text-emerald-700 underline">Approve correction</button></form>}</div>)}</div> : <p className="mt-3 text-sm text-slate-600">No corrections recorded.</p>}</section>
    <details className="surface-card mt-8"><summary className="cursor-pointer font-bold">Finance action history</summary><div className="mt-4 space-y-2 text-xs text-slate-600">{audit.map(item => <p key={item.id}>{item.createdAt.toLocaleString("en-PK")} · {item.actor?.name ?? "Former admin"} · {item.action} · {item.targetId}</p>)}</div></details>
  </div></section>;
}
