import { testCookieName } from "./http-cookie";
import assert from "node:assert/strict";
import { createHash, randomBytes } from "node:crypto";
import { mkdir, unlink, writeFile } from "node:fs/promises";
import path from "node:path";
import { test } from "node:test";
import { PrismaClient } from "@prisma/client";
import { hashPassword } from "../src/lib/auth/password";
import { approveStoryContent, approveStoryEvidence, moderateStory, reconcileCompletedWork } from "../src/lib/operations/completed-work";
import { citizenResolution, transitionComplaint } from "../src/lib/operations/cases";
import { setPublicVisibility } from "../src/lib/geo";
import { getPublishedStory } from "../src/lib/completed-work-public";
import { setNgoEvidencePublic } from "../src/lib/operations/ngos";
import { privateStoragePath } from "../src/lib/private-storage";

const base = process.env.AUTH_TEST_BASE_URL;
test("verified completion publishes once; missing approvals, reopening and revocation withdraw it", { skip: !base }, async () => {
  if (!base || !process.env.DATABASE_URL?.includes("auth-test.db")) throw new Error("Use isolated auth-test.db");
  const db = new PrismaClient(), suffix = randomBytes(5).toString("hex");
  const filePaths: string[] = [], userIds: string[] = [];
  let complaintId = "", ngoId = "", projectId = "", storyId = "";
  try {
    const passwordHash = await hashPassword(`story-${suffix}-password`);
    const admin = await db.user.create({ data: { name: "Story admin", email: `story-admin-${suffix}@example.test`, passwordHash, role: "ADMIN" } });
    const citizen = await db.user.create({ data: { name: "Private citizen", email: `story-citizen-${suffix}@example.test`, passwordHash, role: "CITIZEN" } });
    userIds.push(admin.id, citizen.id);
    const adminToken = randomBytes(32).toString("hex");
    await db.session.create({ data: { userId: admin.id, tokenHash: createHash("sha256").update(adminToken).digest("hex"), expiresAt: new Date(Date.now() + 60_000) } });
    const adminActor = { id: admin.id, role: admin.role }, citizenActor = { id: citizen.id, role: citizen.role };
    const complaint = await db.complaint.create({ data: { reference: `KFX-STORY-${suffix.toUpperCase()}`, title: "PRIVATE HOME TITLE", description: "PRIVATE HOME DESCRIPTION", category: "Roads", area: "Private home address", district: "East", latitude: 24.91, longitude: 67.10, userId: citizen.id } }); complaintId = complaint.id;
    const makeImage = async (stage: "BEFORE" | "AFTER") => {
      const storageKey = `${randomBytes(20).toString("hex")}.png`;
      const filePath = privateStoragePath(storageKey);
      await mkdir(path.dirname(filePath), { recursive: true });
      await writeFile(filePath, Buffer.from("89504e470d0a1a0a0000000d49484452", "hex"), { flag: "wx" }); filePaths.push(filePath);
      return db.evidence.create({ data: { complaintId, uploaderId: admin.id, stage, visibility: "OWNER", storageKey, originalName: `${stage}.png`, mimeType: "image/png", size: 16, note: "PRIVATE FIELD NOTE" } });
    };
    const before = await makeImage("BEFORE"), after = await makeImage("AFTER");
    await assert.rejects(() => approveStoryContent(citizenActor, complaintId, "A public road surface was damaged near the junction.", "The team documented and repaired the public road surface."));
    await approveStoryContent(adminActor, complaintId, "A public road surface was damaged near the junction.", "The team documented and repaired the public road surface.");
    assert.ok((await db.completedWorkStory.findUniqueOrThrow({ where: { complaintId } })).contentApprovedAt);
    await transitionComplaint(adminActor, complaintId, "UNDER_REVIEW", "Starting review");
    await transitionComplaint(adminActor, complaintId, "VERIFIED", "Field verification recorded");
    await setPublicVisibility(adminActor, complaintId, true, "Road surface repaired near junction", "Gulshan-e-Iqbal");
    const ngo = await db.partnerNgo.create({ data: { name: `Verified Partner ${suffix}`, contactPerson: "PRIVATE CONTACT", status: "ACTIVE", verifiedAt: new Date(), verifiedById: admin.id, serviceAreas: "East", expertise: "Road work" } }); ngoId = ngo.id;
    const project = await db.ngoProject.create({ data: { ngoId, complaintId, title: "Approved road project", description: "PRIVATE PROJECT DETAILS", status: "ACTIVE", publicApproved: true, publicSummary: "A verified public road project is underway." } }); projectId = project.id;
    await db.evidence.update({ where: { id: after.id }, data: { ngoProjectId: projectId } });
    await transitionComplaint(adminActor, complaintId, "RESOLUTION_PROPOSED", "Completion offered for review");
    const preApproval = await db.completedWorkStory.findUniqueOrThrow({ where: { complaintId } });
    assert.equal(preApproval.status, "DRAFT");
    assert.match(preApproval.holdReason ?? "", /Resolution verification pending|BEFORE photo awaiting/);
    const adminView = await (await fetch(`${base}/admin/projects/${complaintId}`, { headers: { Cookie: `${testCookieName}=${adminToken}` } })).text();
    assert.match(adminView, /BEFORE photo awaiting public approval/);
    assert.match(adminView, /Summaries approved/);
    assert.equal((await fetch(`${base}/admin/projects`, { headers: { Cookie: `${testCookieName}=${adminToken}` } })).status, 200);
    await citizenResolution(citizenActor, complaintId, "CONFIRM");
    let story = await db.completedWorkStory.findUniqueOrThrow({ where: { complaintId } });
    storyId = story.id;
    assert.equal(story.status, "DRAFT");
    assert.equal((await fetch(`${base}/projects/completed/${story.id}`)).status, 404);
    assert.equal((await fetch(`${base}/api/projects/completed/${story.id}/media/before`)).status, 404);
    await assert.rejects(() => approveStoryEvidence(citizenActor, before.id, true, true));
    await assert.rejects(() => approveStoryEvidence(adminActor, before.id, true, false));
    await approveStoryEvidence(adminActor, before.id, true, true);
    story = await db.completedWorkStory.findUniqueOrThrow({ where: { complaintId } });
    assert.equal(story.status, "DRAFT");
    assert.match(story.holdReason ?? "", /AFTER photo awaiting/);
    await approveStoryEvidence(adminActor, after.id, true, true);
    story = await db.completedWorkStory.findUniqueOrThrow({ where: { complaintId } });
    assert.equal(story.status, "PUBLISHED");
    assert.equal((await getPublishedStory(story.id))?.reference, complaint.reference);
    const publishedCount = await db.auditLog.count({ where: { targetType: "CompletedWorkStory", targetId: story.id, action: "STORY_PUBLISHED" } });
    await db.$transaction(tx => reconcileCompletedWork(tx, complaintId, admin.id));
    await db.$transaction(tx => reconcileCompletedWork(tx, complaintId, admin.id));
    assert.equal(await db.completedWorkStory.count({ where: { complaintId } }), 1);
    assert.equal(await db.auditLog.count({ where: { targetType: "CompletedWorkStory", targetId: story.id, action: "STORY_PUBLISHED" } }), publishedCount);
    const publicPage = await (await fetch(`${base}/projects/completed/${story.id}`)).text();
    assert.match(publicPage, /Road surface repaired near junction|Verified Partner/);
    assert.doesNotMatch(publicPage, /PRIVATE HOME TITLE|PRIVATE HOME DESCRIPTION|PRIVATE FIELD NOTE|PRIVATE CONTACT|PRIVATE PROJECT DETAILS|story-citizen/);
    assert.match(publicPage, new RegExp(`/map/case/${complaintId}`));
    assert.equal((await fetch(`${base}/api/projects/completed/${story.id}/media/before`)).status, 200);
    assert.equal((await fetch(`${base}/api/projects/completed/${story.id}/media/after`)).status, 200);
    const listing = await (await fetch(`${base}/projects`)).text();
    assert.equal((listing.match(/Road surface repaired near junction/g) ?? []).length > 0, true);
    assert.doesNotMatch(listing, /Approved road project/);
    assert.doesNotMatch(listing, /PRIVATE HOME TITLE|PRIVATE HOME DESCRIPTION/);
    assert.match(await (await fetch(`${base}/projects/${projectId}`)).text(), /View the before and after story/);
    await setPublicVisibility(adminActor, complaintId, false);
    assert.equal((await db.complaint.findUniqueOrThrow({ where: { id: complaintId } })).publicVisible, false);
    assert.equal((await db.completedWorkStory.findUniqueOrThrow({ where: { complaintId } })).status, "PUBLISHED", "removing a map marker must not withdraw an independently approved story");
    assert.equal((await getPublishedStory(story.id))?.reference, complaint.reference);
    const storyWithoutMap = await (await fetch(`${base}/projects/completed/${story.id}`)).text();
    assert.match(storyWithoutMap, new RegExp(`/track\\?ref=${complaint.reference}`));
    assert.doesNotMatch(storyWithoutMap, new RegExp(`/map/case/${complaintId}`));
    await setPublicVisibility(adminActor, complaintId, true, "Road surface repaired near junction", "Gulshan-e-Iqbal");
    const tracking = await (await fetch(`${base}/map/case/${complaintId}`)).text();
    assert.doesNotMatch(tracking, /PRIVATE HOME TITLE|PRIVATE HOME DESCRIPTION|PRIVATE FIELD NOTE/);
    await citizenResolution(citizenActor, complaintId, "REOPEN", "The surface failed again after the initial work.");
    story = await db.completedWorkStory.findUniqueOrThrow({ where: { complaintId } });
    assert.equal(story.status, "WITHDRAWN");
    assert.equal((await fetch(`${base}/projects/completed/${story.id}`)).status, 404);
    assert.equal((await fetch(`${base}/api/projects/completed/${story.id}/media/after`)).status, 404);
    await transitionComplaint(adminActor, complaintId, "VERIFIED", "Rechecked the reported road surface");
    await transitionComplaint(adminActor, complaintId, "RESOLUTION_PROPOSED", "Repair reviewed again");
    await citizenResolution(citizenActor, complaintId, "DISPUTE", "The surface still needs more work at this location.");
    assert.equal((await db.completedWorkStory.findUniqueOrThrow({ where: { complaintId } })).status, "WITHDRAWN");
    await transitionComplaint(adminActor, complaintId, "VERIFIED", "Another field verification was recorded");
    await transitionComplaint(adminActor, complaintId, "RESOLUTION_PROPOSED", "Revised repair reviewed");
    await citizenResolution(citizenActor, complaintId, "CONFIRM");
    assert.equal((await db.completedWorkStory.findUniqueOrThrow({ where: { complaintId } })).status, "PUBLISHED");
    await approveStoryEvidence(adminActor, before.id, false, false);
    assert.equal((await db.completedWorkStory.findUniqueOrThrow({ where: { complaintId } })).status, "WITHDRAWN");
    assert.equal((await fetch(`${base}/api/projects/completed/${story.id}/media/before`)).status, 404);
    await approveStoryEvidence(adminActor, before.id, true, true);
    await moderateStory(adminActor, complaintId, true);
    assert.equal((await fetch(`${base}/projects/completed/${story.id}`)).status, 404);
    await moderateStory(adminActor, complaintId, false);
    assert.equal((await db.completedWorkStory.findUniqueOrThrow({ where: { complaintId } })).status, "PUBLISHED");
    await setNgoEvidencePublic(adminActor, after.id, false, false);
    assert.equal((await db.completedWorkStory.findUniqueOrThrow({ where: { complaintId } })).status, "WITHDRAWN");
    assert.equal((await fetch(`${base}/api/projects/completed/${story.id}/media/after`)).status, 404);
    const token = randomBytes(32).toString("hex");
    await db.session.create({ data: { userId: citizen.id, tokenHash: createHash("sha256").update(token).digest("hex"), expiresAt: new Date(Date.now() + 60_000) } });
    assert.equal((await fetch(`${base}/admin/projects`, { headers: { Cookie: `${testCookieName}=${token}` }, redirect: "manual" })).status, 307);
  } finally {
    if (projectId) await db.ngoProject.delete({ where: { id: projectId } });
    if (ngoId) await db.partnerNgo.delete({ where: { id: ngoId } });
    if (complaintId) await db.complaint.delete({ where: { id: complaintId } });
    await db.auditLog.deleteMany({ where: { actorId: { in: userIds } } });
    if (storyId) await db.auditLog.deleteMany({ where: { targetType: "CompletedWorkStory", targetId: storyId, actorId: null } });
    await db.user.deleteMany({ where: { id: { in: userIds } } });
    for (const filePath of filePaths) await unlink(filePath).catch(() => undefined);
    await db.$disconnect();
  }
});
