import { testCookieName } from "./http-cookie";
import assert from "node:assert/strict";
import { createHash, randomBytes } from "node:crypto";
import { unlink } from "node:fs/promises";
import path from "node:path";
import { test } from "node:test";
import { PrismaClient } from "@prisma/client";
import { hashPassword } from "../src/lib/auth/password";
import { amountPkr, configureWallet, donationReceiptDirectory, recordExpense, reviewDonation, saveCampaign, submitDonation, validateReceipt } from "../src/lib/donations";
import { OperationError } from "../src/lib/operations/common";

const base = process.env.AUTH_TEST_BASE_URL;
test("donations require independent admin verification and keep donor data private", { skip: !base }, async () => {
  if (!base) return;
  if (!process.env.DATABASE_URL?.includes("auth-test.db")) throw new Error("Donation tests require isolated auth-test.db");
  const db = new PrismaClient();
  const suffix = randomBytes(5).toString("hex");
  const userIds: string[] = [], complaintIds: string[] = [], campaignIds: string[] = [], walletIds: string[] = [], intentIds: string[] = [], expenseIds: string[] = [], receiptKeys: string[] = [];
  let taskId: string | null = null;
  const png = new File([Buffer.from([137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 0])], "proof.png", { type: "image/png" });
  async function expectCode(work: () => Promise<unknown>, code: OperationError["code"]) { await assert.rejects(work, error => error instanceof OperationError && error.code === code); }
  async function cookie(userId: string) { const token = randomBytes(32).toString("hex"); await db.session.create({ data: { userId, tokenHash: createHash("sha256").update(token).digest("hex"), expiresAt: new Date(Date.now() + 60_000) } }); return `${testCookieName}=${token}`; }
  try {
    for (const value of ["0", "99", "-100", "1.5", "1000001", "not-money"]) assert.throws(() => amountPkr(value));
    assert.equal(amountPkr("1000"), 1000);
    await expectCode(() => validateReceipt(new File(["<svg onload=alert(1)>"], "fake.png", { type: "image/png" })), "invalid");
    await expectCode(() => validateReceipt(new File([new Uint8Array(3 * 1024 * 1024 + 1)], "large.png", { type: "image/png" })), "invalid");
    const passwordHash = await hashPassword(`donation-test-${suffix}`);
    const admin = await db.user.create({ data: { name: "Donations Admin", email: `donations-admin-${suffix}@example.test`, passwordHash, role: "ADMIN" } });
    const citizen = await db.user.create({ data: { name: "Donor Citizen", email: `donations-citizen-${suffix}@example.test`, passwordHash, role: "CITIZEN" } });
    userIds.push(admin.id, citizen.id);
    const adminActor = { id: admin.id, role: admin.role }, citizenActor = { id: citizen.id, role: citizen.role };
    const walletInput = { method: "EASYPAISA", accountNumber: "03460000000", accountTitle: "Test Karachi Fix", instructions: "Transfer only after checking the account title.", enabled: true, confirmed: true };
    await expectCode(() => configureWallet(citizenActor, walletInput), "forbidden");
    await expectCode(() => configureWallet(adminActor, { ...walletInput, confirmed: false }), "invalid");
    const wallet = await configureWallet(adminActor, { ...walletInput, enabled: false });
    walletIds.push(wallet.id);
    assert.doesNotMatch(await (await fetch(`${base}/donate`)).text(), /03460000000/);
    await configureWallet(adminActor, walletInput);
    assert.match(await (await fetch(`${base}/donate`)).text(), /03460000000/);
    const complaint = await db.complaint.create({ data: { reference: `KFX-DON-${suffix.toUpperCase()}`, title: "Community issue", description: "A public issue requiring community work.", category: "Other", area: "Karachi", userId: citizen.id, status: "SUBMITTED" } });
    complaintIds.push(complaint.id);
    const campaignInput = { slug: `community-project-${suffix}`, title: "Community repair project", description: "A documented community project addressing a verified issue.", complaintId: complaint.id, verificationNote: "Karachi Fix reviewed the project purpose and supporting field record.", status: "PUBLISHED" };
    await expectCode(() => saveCampaign(adminActor, campaignInput), "conflict");
    await db.complaint.update({ where: { id: complaint.id }, data: { status: "VERIFIED" } });
    await db.caseEvent.create({ data: { complaintId: complaint.id, actorId: admin.id, kind: "VERIFIED", summary: "Field verified", visibility: "INTERNAL" } });
    const task = await db.task.create({ data: { code: `TASK-DON-${suffix.toUpperCase()}`, complaintId: complaint.id, createdById: admin.id, type: "FIELD_CHECK", priority: "NORMAL", deadline: new Date(Date.now() + 86_400_000), instructions: "Test task priority stays independent from donations." } });
    taskId = task.id;
    const campaign = await saveCampaign(adminActor, campaignInput);
    campaignIds.push(campaign.id);
    assert.match(await (await fetch(`${base}/donate?ref=${complaint.reference}`)).text(), /Community repair project/);
    const file = await validateReceipt(png);
    assert.equal(file?.mime, "image/png");
    const intent = await submitDonation({ walletId: wallet.id, campaignId: campaign.id, amount: "1000", transactionReference: `REF-${suffix}`, donorName: "Private Donor", donorEmail: `private-${suffix}@example.test`, receipt: png, donorUserId: citizen.id });
    intentIds.push(intent.id);
    if (intent.receiptKey) receiptKeys.push(intent.receiptKey);
    assert.equal(intent.status, "PENDING");
    assert.equal((await db.complaint.findUniqueOrThrow({ where: { id: complaint.id } })).status, "VERIFIED");
    assert.equal((await db.task.findUniqueOrThrow({ where: { id: task.id } })).priority, "NORMAL");
    await assert.rejects(() => submitDonation({ walletId: wallet.id, campaignId: campaign.id, amount: "1000", transactionReference: `REF-${suffix}`, receipt: null }));
    assert.equal(await db.donationIntent.count({ where: { walletId: wallet.id, transactionReference: `REF-${suffix}`.toUpperCase() } }), 1);
    const publicBefore = await (await fetch(`${base}/transparency`)).text();
    assert.match(publicBefore, /PKR (?:<!-- -->)?0/);
    assert.doesNotMatch(publicBefore, /Private Donor|REF-|private-.*@example\.test/);
    const citizenCookie = await cookie(citizen.id), adminCookie = await cookie(admin.id);
    assert.equal((await fetch(`${base}/admin/donations`, { redirect: "manual" })).status, 307);
    assert.equal((await fetch(`${base}/admin/donations`, { headers: { Cookie: citizenCookie }, redirect: "manual" })).status, 307);
    assert.equal((await fetch(`${base}/admin/donations`, { headers: { Cookie: adminCookie } })).status, 200);
    assert.equal((await fetch(`${base}/api/donations/receipts/${intent.id}`)).status, 404);
    assert.equal((await fetch(`${base}/api/donations/receipts/${intent.id}`, { headers: { Cookie: citizenCookie } })).status, 404);
    assert.equal((await fetch(`${base}/api/donations/receipts/${intent.id}`, { headers: { Cookie: adminCookie } })).status, 200);
    await expectCode(() => reviewDonation(citizenActor, intent.id, "VERIFIED", "Checked the actual receiving account statement.", true), "forbidden");
    await expectCode(() => reviewDonation(adminActor, intent.id, "VERIFIED", "Checked the actual receiving account statement.", false), "invalid");
    assert.equal((await db.donationIntent.findUniqueOrThrow({ where: { id: intent.id } })).status, "PENDING");
    await reviewDonation(adminActor, intent.id, "VERIFIED", "Independently matched the transfer in the receiving account.", true);
    assert.equal((await db.donationVerification.count({ where: { intentId: intent.id } })), 1);
    const publicAfter = await (await fetch(`${base}/transparency`)).text();
    assert.match(publicAfter, /PKR (?:<!-- -->)?1,000/);
    assert.doesNotMatch(publicAfter, /Private Donor|REF-|private-.*@example\.test/);
    await expectCode(() => reviewDonation(adminActor, intent.id, "VERIFIED", "Checked the account a second time; still matched.", true), "conflict");
    await reviewDonation(adminActor, intent.id, "REFUNDED", "Refunded the transfer and checked the receiving account.", true);
    assert.match(await (await fetch(`${base}/transparency`)).text(), /PKR (?:<!-- -->)?0/);
    const expense = await recordExpense(adminActor, { amount: "500", purpose: "Community supplies", documentation: "Invoice KF TEST 123 for community work", spentAt: new Date().toISOString(), publish: true });
    expenseIds.push(expense.id);
    assert.match(await (await fetch(`${base}/transparency`)).text(), /Community supplies/);
    assert.equal((await db.complaint.findUniqueOrThrow({ where: { id: complaint.id } })).status, "VERIFIED");
    assert.equal((await db.task.findUniqueOrThrow({ where: { id: task.id } })).priority, "NORMAL");
  } finally {
    if (expenseIds.length) await db.donationExpense.deleteMany({ where: { id: { in: expenseIds } } });
    if (intentIds.length) { await db.donationVerification.deleteMany({ where: { intentId: { in: intentIds } } }); await db.donationIntent.deleteMany({ where: { id: { in: intentIds } } }); }
    if (campaignIds.length) await db.donationCampaign.deleteMany({ where: { id: { in: campaignIds } } });
    if (walletIds.length) await db.walletAccount.deleteMany({ where: { id: { in: walletIds } } });
    if (taskId) await db.task.delete({ where: { id: taskId } });
    if (complaintIds.length) await db.complaint.deleteMany({ where: { id: { in: complaintIds } } });
    if (userIds.length) await db.user.deleteMany({ where: { id: { in: userIds } } });
    for (const key of receiptKeys) await unlink(path.join(donationReceiptDirectory, key)).catch(() => undefined);
    await db.$disconnect();
  }
});
