import assert from "node:assert/strict";
import { randomBytes, randomUUID } from "node:crypto";
import { test } from "node:test";
import { PrismaClient } from "@prisma/client";
import { detectorHistoryState, duplicateScore, publicDuplicateSuggestions, reviewCaseLink, setComplaintSupport, submissionDuplicateCandidates } from "../src/lib/duplicates";
import { submitCitizenReport } from "../src/lib/operations/report";
import { transitionComplaint } from "../src/lib/operations/cases";

test("[QA TEST] related reports remain separate, admin links are audited and support is private", { skip: !process.env.DATABASE_URL?.includes("auth-test.db") }, async () => {
  if (!process.env.DATABASE_URL?.includes("auth-test.db")) throw new Error("Use isolated auth-test.db");
  const db = new PrismaClient(), suffix = randomBytes(6).toString("hex"), userIds: string[] = [], caseIds: string[] = [];
  try {
    const city = await db.city.findUniqueOrThrow({ where: { slug: "karachi" } });
    const [admin, owner, supporter, stranger] = await Promise.all(["ADMIN", "CITIZEN", "VOLUNTEER", "CITIZEN"].map(async (role, index) => {
      const user = await db.user.create({ data: { name: `[QA TEST] Duplicate ${index}`, email: `duplicate-${index}-${suffix}@example.test`, passwordHash: "test-only", role: role as "ADMIN" | "CITIZEN" | "VOLUNTEER" } });
      userIds.push(user.id); return user;
    }));
    const primary = await db.complaint.create({ data: { cityId: city.id, userId: owner.id, reference: `KFX-${randomBytes(8).toString("hex").toUpperCase()}`, title: "[QA TEST] Streetlight pole 5", category: "Streetlights", description: "[QA TEST] Private reporter notes never leave the public API.", district: "East", area: "Gulshan-e-Iqbal", status: "VERIFIED", publicVisible: true, publicApprovedAt: new Date(), publicTitle: "[QA TEST] Streetlight pole 5", publicArea: "Gulshan-e-Iqbal QA area", latitude: 24.92, longitude: 67.09, publicLatitude: 24.92, publicLongitude: 67.09 } }); caseIds.push(primary.id);
    const second = await db.complaint.create({ data: { cityId: city.id, userId: owner.id, reference: `KFX-${randomBytes(8).toString("hex").toUpperCase()}`, title: "[QA TEST] Streetlight pole 5 across the lane", category: "Streetlights", description: "[QA TEST] A separate approved fictional field report.", district: "East", area: "Gulshan-e-Iqbal", status: "VERIFIED", publicVisible: true, publicApprovedAt: new Date(), publicTitle: "[QA TEST] Streetlight pole 5 across the lane", publicArea: "Gulshan-e-Iqbal QA area", publicLatitude: 24.92, publicLongitude: 67.09 } }); caseIds.push(second.id);
    const query = { cityId: city.id, title: "[QA TEST] Streetlight pole 5", description: "Pole 5 has no light", category: "Streetlights", district: "East", area: "Gulshan-e-Iqbal" };
    assert.equal((await publicDuplicateSuggestions(query))[0]?.likelySameIssue, true);
    assert.equal((await publicDuplicateSuggestions({ ...query, title: "[QA TEST] Unrelated transformer failure", description: "A different piece of infrastructure failed" }))[0]?.likelySameIssue, false);
    assert.equal((await publicDuplicateSuggestions({ ...query, point: { latitude: 24.9201, longitude: 67.0901 } }))[0]?.id, primary.id);
    assert.equal((await publicDuplicateSuggestions({ ...query, category: "Roads & potholes" })).length, 0);
    assert.equal((await publicDuplicateSuggestions({ ...query, area: "Saddar" })).length, 0);
    assert.equal(duplicateScore({ ...query, title: "[QA TEST] Streetlight pole 6", description: "Pole 6 is dark" }, { title: primary.publicTitle!, category: primary.category, district: primary.district, area: primary.publicArea! }).likelySameIssue, false);
    const submitted = await submitCitizenReport({ id: supporter.id, role: "VOLUNTEER" }, { citySlug: "karachi", submissionKey: randomUUID(), title: query.title, category: query.category, description: "[QA TEST] This is the same fictional pole 5 outage.", district: query.district, area: query.area, manualArea: false, photos: [] }); caseIds.push(submitted.id);
    const link = await db.caseLink.findFirstOrThrow({ where: { sourceComplaintId: submitted.id, targetComplaintId: primary.id } });
    assert.equal(link.status, "SUGGESTED");
    const detectorRun = await db.auditLog.findFirstOrThrow({ where: { action: "DUPLICATE_DETECTION_RUN", targetId: submitted.id } });
    assert.match(detectorRun.details ?? "", /"candidateCount":2/);
    assert.equal(detectorHistoryState(JSON.parse(detectorRun.details ?? "{}"), ["SUGGESTED", "SUGGESTED"]), "Pending review");
    const secondLink = await db.caseLink.findFirstOrThrow({ where: { sourceComplaintId: submitted.id, targetComplaintId: second.id } });
    await reviewCaseLink({ id: admin.id, role: "ADMIN" }, secondLink.id, "REJECTED", "[QA TEST] Separate nearby fixture");
    assert.equal(detectorHistoryState(JSON.parse(detectorRun.details ?? "{}"), ["REJECTED", "SUGGESTED"]), "Pending review");
    await assert.rejects(reviewCaseLink({ id: supporter.id, role: "VOLUNTEER" }, link.id, "LINKED", "[QA TEST] Same pole"), { code: "forbidden" });
    await reviewCaseLink({ id: admin.id, role: "ADMIN" }, link.id, "LINKED", "[QA TEST] Same fictional pole");
    assert.equal((await db.caseLink.findUniqueOrThrow({ where: { id: link.id } })).status, "LINKED");
    assert.equal((await db.complaint.findUniqueOrThrow({ where: { id: submitted.id } })).status, "SUBMITTED", "linking must not copy primary status");
    const originalSla = await db.complaintSlaSnapshot.findUniqueOrThrow({ where: { complaintId: submitted.id } });
    await transitionComplaint({ id: admin.id, role: "ADMIN" }, primary.id, "ASSIGNED", "[QA TEST] Fictional primary assignment");
    assert.equal((await db.complaint.findUniqueOrThrow({ where: { id: submitted.id } })).status, "SUBMITTED", "primary progress must not propagate");
    assert.equal((await db.complaintSlaSnapshot.findUniqueOrThrow({ where: { complaintId: submitted.id } })).capturedAt.getTime(), originalSla.capturedAt.getTime(), "linked reports keep their own SLA snapshot");
    assert.equal(await db.caseEvent.count({ where: { complaintId: submitted.id, kind: "CASE_LINK_LINKED", visibility: "INTERNAL" } }), 1);
    await reviewCaseLink({ id: admin.id, role: "ADMIN" }, link.id, "UNLINKED", "[QA TEST] Correcting relationship");
    await reviewCaseLink({ id: admin.id, role: "ADMIN" }, link.id, "REJECTED", "[QA TEST] Different issue after review");
    assert.equal((await db.caseLink.findUniqueOrThrow({ where: { id: link.id } })).status, "REJECTED");
    assert.equal(detectorHistoryState(JSON.parse(detectorRun.details ?? "{}"), ["REJECTED", "REJECTED"]), "Reviewed / rejected");
    await db.complaint.update({ where: { id: primary.id }, data: { status: "RESOLVED" } });
    await db.complaint.update({ where: { id: second.id }, data: { status: "RESOLVED" } });
    const historical = (await publicDuplicateSuggestions(query)).find(item => item.id === primary.id);
    assert.equal(historical?.likelySameIssue, false, "resolved public reports cannot be linked as active duplicates");
    assert.equal(historical?.status, "RESOLVED");
    assert.equal((await submissionDuplicateCandidates(query)).reason, "NO_ELIGIBLE_ACTIVE_PARTNER");
    const historicalOnly = await submitCitizenReport({ id: stranger.id, role: "CITIZEN" }, { citySlug: "karachi", submissionKey: randomUUID(), title: query.title, category: query.category, description: "[QA TEST] Fictional pole 5 remains a separate report.", district: query.district, area: query.area, manualArea: false, photos: [] }); caseIds.push(historicalOnly.id);
    assert.equal(await db.caseLink.count({ where: { sourceComplaintId: historicalOnly.id } }), 0);
    assert.match((await db.auditLog.findFirstOrThrow({ where: { action: "DUPLICATE_DETECTION_RUN", targetId: historicalOnly.id } })).details ?? "", /NO_ELIGIBLE_ACTIVE_PARTNER/);
    assert.equal(detectorHistoryState(null, []), "Never ran");
    await assert.rejects(reviewCaseLink({ id: admin.id, role: "ADMIN" }, secondLink.id, "LINKED", "[QA TEST] Too late to link"), { code: "conflict" });
    assert.equal((await db.complaint.findUniqueOrThrow({ where: { id: submitted.id } })).userId, supporter.id);
    await assert.rejects(setComplaintSupport({ id: owner.id, role: "CITIZEN" }, primary.id, true), { code: "forbidden" });
    await setComplaintSupport({ id: stranger.id, role: "CITIZEN" }, primary.id, true);
    await setComplaintSupport({ id: stranger.id, role: "CITIZEN" }, primary.id, true);
    assert.equal(await db.complaintSupport.count({ where: { complaintId: primary.id, active: true } }), 1);
    await setComplaintSupport({ id: stranger.id, role: "CITIZEN" }, primary.id, false);
    assert.equal(await db.complaintSupport.count({ where: { complaintId: primary.id, active: true } }), 0);
    assert.equal(await db.notification.count({ where: { userId: supporter.id, complaintId: submitted.id, title: "Case relationship reviewed" } }), 4);
    const publicResult = JSON.stringify(await publicDuplicateSuggestions(query));
    assert.doesNotMatch(publicResult, /Private reporter notes|@example\.test|24\.9201/);
  } finally {
    await db.complaintSupport.deleteMany({ where: { complaintId: { in: caseIds } } });
    await db.caseLink.deleteMany({ where: { sourceComplaintId: { in: caseIds } } });
    await db.notificationDeliveryAttempt.deleteMany({ where: { outbox: { complaintId: { in: caseIds } } } });
    await db.notificationOutbox.deleteMany({ where: { complaintId: { in: caseIds } } });
    await db.notification.deleteMany({ where: { complaintId: { in: caseIds } } });
    await db.caseEvent.deleteMany({ where: { complaintId: { in: caseIds } } });
    await db.complaintSlaSnapshot.deleteMany({ where: { complaintId: { in: caseIds } } });
    await db.complaint.deleteMany({ where: { id: { in: caseIds } } });
    await db.auditLog.deleteMany({ where: { actorId: { in: userIds } } });
    await db.user.deleteMany({ where: { id: { in: userIds } } });
    await db.$disconnect();
  }
});
