import assert from "node:assert/strict";
import { randomBytes } from "node:crypto";
import { test } from "node:test";
import { PrismaClient } from "@prisma/client";
import { hashPassword } from "../src/lib/auth/password";
import { approveSlaPolicy, recordSlaMilestone, slaStages, snapshotSlaAtSubmission } from "../src/lib/sla";
import { cancelResolutionReminders, externalTrackLink, messageAdapter, pakistanMobile, processNotificationOutbox, queueCitizenNotice, reminderHours, scheduleResolutionReminders } from "../src/lib/notifications";
import { citizenResolution, transitionComplaint } from "../src/lib/operations/cases";
import { saveCitizenProfile } from "../src/lib/citizen-profile";

test("opt-in notifications, durable mock retries, reminder cancellation and historical SLA targets", { skip: !process.env.DATABASE_URL?.includes("auth-test.db") }, async () => {
  if (!process.env.DATABASE_URL?.includes("auth-test.db")) throw new Error("Use isolated auth-test.db");
  const db = new PrismaClient(), suffix = randomBytes(6).toString("hex");
  const ids: string[] = [], userIds: string[] = [], policyIds: string[] = [];
  const priorMode = process.env.NOTIFICATION_PROVIDER_MODE, priorFail = process.env.NOTIFICATION_MOCK_FAIL_ONCE;
  try {
    const city = await db.city.findUniqueOrThrow({ where: { slug: "karachi" } });
    const passwordHash = await hashPassword(`qa-${suffix}-password`);
    const admin = await db.user.create({ data: { name: "[QA TEST] Admin", email: `qa-sla-admin-${suffix}@example.test`, passwordHash, role: "ADMIN" } }); userIds.push(admin.id);
    const owner = await db.user.create({ data: { name: "[QA TEST] Citizen Volunteer", email: `qa-sla-owner-${suffix}@example.test`, passwordHash, role: "VOLUNTEER" } }); userIds.push(owner.id);
    const stranger = await db.user.create({ data: { name: "[QA TEST] Stranger", email: `qa-sla-other-${suffix}@example.test`, passwordHash, role: "CITIZEN" } }); userIds.push(stranger.id);
    const makeComplaint = async () => { const row = await db.complaint.create({ data: { userId: owner.id, cityId: city.id, reference: `KFX-${randomBytes(8).toString("hex").toUpperCase()}`, title: "[QA TEST] Fictional streetlight", category: "Other", description: "[QA TEST] Fictional case for notification and SLA tests.", district: "East", area: "Gulshan-e-Iqbal" } }); ids.push(row.id); return row; };
    const oldCase = await makeComplaint();
    await db.$transaction(tx => snapshotSlaAtSubmission(tx, oldCase));
    assert.equal((await db.complaintSlaSnapshot.findUniqueOrThrow({ where: { complaintId: oldCase.id } })).firstReviewTargetAt, null);
    await assert.rejects(approveSlaPolicy({ id: owner.id, role: "VOLUNTEER" }, city.id, "Other", 12, 24, 120), { code: "forbidden" });
    const policy = await approveSlaPolicy({ id: admin.id, role: "ADMIN" }, city.id, "Other", 12, 24, 120); policyIds.push(policy.id);
    const current = await makeComplaint();
    await db.$transaction(tx => snapshotSlaAtSubmission(tx, current));
    const snapshot = await db.complaintSlaSnapshot.findUniqueOrThrow({ where: { complaintId: current.id } });
    assert.equal(snapshot.policyVersion, policy.version);
    assert.equal(snapshot.firstReviewTargetAt?.getTime(), current.createdAt.getTime() + 12 * 3_600_000);
    assert.equal((await db.complaintSlaSnapshot.findUniqueOrThrow({ where: { complaintId: oldCase.id } })).firstReviewTargetAt, null, "new policy must not rewrite an old target");
    assert.equal(slaStages(snapshot, new Date(current.createdAt.getTime() + 11 * 3_600_000))[0].state, "APPROACHING");
    assert.equal(slaStages(snapshot, new Date(current.createdAt.getTime() + 13 * 3_600_000))[0].state, "OVERDUE");
    assert.equal(slaStages({ ...snapshot, firstReviewedAt: new Date(current.createdAt.getTime() + 13 * 3_600_000) })[0].state, "DONE_LATE");
    await db.$transaction(tx => recordSlaMilestone(tx, current.id, "UNDER_REVIEW", current.createdAt));
    assert.equal(slaStages(await db.complaintSlaSnapshot.findUniqueOrThrow({ where: { complaintId: current.id } }))[0].state, "DONE");
    await transitionComplaint({ id: admin.id, role: "ADMIN" }, current.id, "UNDER_REVIEW", "[QA TEST] Reviewing fictional case");
    await transitionComplaint({ id: admin.id, role: "ADMIN" }, current.id, "VERIFIED", "[QA TEST] Fictional report verified");
    assert.equal(await db.notification.count({ where: { userId: owner.id, complaintId: current.id, kind: { in: ["UNDER_REVIEW", "VERIFIED"] } } }), 2);
    await transitionComplaint({ id: admin.id, role: "ADMIN" }, current.id, "BLOCKED", "More information requested: [QA TEST] Please clarify the fictional report");
    assert.equal(await db.notification.count({ where: { userId: owner.id, complaintId: current.id, kind: "INFORMATION_REQUESTED" } }), 1);
    assert.equal(pakistanMobile("not-a-mobile"), null);
    assert.match(externalTrackLink(`/track?ref=${current.reference}`) ?? "", /\/track\?ref=KFX-/);
    assert.equal(externalTrackLink("/api/evidence/private"), null);
    assert.deepEqual(reminderHours("24,72,96"), [24, 72]);
    await assert.rejects(saveCitizenProfile({ id: owner.id, role: "VOLUNTEER" }, { name: owner.name, phone: "12345", citySlug: "karachi", smsOptIn: true }), /phone|mobile/i);
    await saveCitizenProfile({ id: owner.id, role: "VOLUNTEER" }, { name: owner.name, phone: "03001234567", citySlug: "karachi", smsOptIn: true, whatsappOptIn: true });
    await db.$transaction(async tx => { for (let i = 0; i < 2; i++) await queueCitizenNotice(tx, { userId: owner.id, complaintId: current.id, reference: current.reference, kind: "TASK_PROGRESS", title: "Field progress", eventKey: `qa-${suffix}` }); });
    assert.equal(await db.notification.count({ where: { userId: owner.id, complaintId: current.id, kind: "TASK_PROGRESS" } }), 1);
    assert.equal(await db.notificationOutbox.count({ where: { userId: owner.id, complaintId: current.id, kind: "TASK_PROGRESS" } }), 2);
    process.env.NOTIFICATION_PROVIDER_MODE = "mock"; process.env.NOTIFICATION_MOCK_FAIL_ONCE = "1";
    await processNotificationOutbox(new Date(Date.now() + 5_000));
    assert.equal(await db.notificationOutbox.count({ where: { complaintId: current.id, kind: "TASK_PROGRESS", status: "RETRY" } }), 2);
    await processNotificationOutbox(new Date(Date.now() + 5 * 60_000));
    assert.equal(await db.notificationOutbox.count({ where: { complaintId: current.id, kind: "TASK_PROGRESS", status: "DELIVERED" } }), 2);
    assert.equal(await db.notificationDeliveryAttempt.count({ where: { outbox: { complaintId: current.id, kind: "TASK_PROGRESS" } } }), 4);
    await db.complaint.update({ where: { id: current.id }, data: { status: "RESOLUTION_PROPOSED" } });
    await db.$transaction(tx => scheduleResolutionReminders(tx, { userId: owner.id, complaintId: current.id, reference: current.reference, proposalEventId: `proposal-${suffix}` }));
    assert.equal(await db.notificationOutbox.count({ where: { complaintId: current.id, kind: "RESOLUTION_REMINDER", status: "PENDING" } }), 6);
    await assert.rejects(citizenResolution({ id: stranger.id, role: "CITIZEN" }, current.id, "DISPUTE", "[QA TEST] This is not my report"), { code: "forbidden" });
    await citizenResolution({ id: owner.id, role: "VOLUNTEER" }, current.id, "DISPUTE", "[QA TEST] Fictional issue still needs work");
    assert.equal((await db.complaint.findUniqueOrThrow({ where: { id: current.id } })).status, "REOPENED");
    assert.equal(await db.notificationOutbox.count({ where: { complaintId: current.id, kind: "RESOLUTION_REMINDER", status: "CANCELLED" } }), 6);
    await db.$transaction(tx => cancelResolutionReminders(tx, current.id));
    await saveCitizenProfile({ id: owner.id, role: "VOLUNTEER" }, { name: owner.name, phone: "03001234567", citySlug: "karachi", smsOptIn: false, whatsappOptIn: false });
    assert.equal((await messageAdapter().send({ channel: "SMS", to: "+923001234567", body: "[QA TEST]", attempt: 2 })).ok, true);
    process.env.NOTIFICATION_PROVIDER_MODE = "disabled";
    assert.deepEqual(await messageAdapter().send({ channel: "SMS", to: "+923001234567", body: "[QA TEST]", attempt: 1 }), { ok: false, code: "provider_unconfigured", retryable: false });
    assert.equal(await db.completedWorkStory.count({ where: { complaintId: current.id } }), 0, "dispute must not publish a story");
  } finally {
    process.env.NOTIFICATION_PROVIDER_MODE = priorMode; process.env.NOTIFICATION_MOCK_FAIL_ONCE = priorFail;
    await db.notificationDeliveryAttempt.deleteMany({ where: { outbox: { complaintId: { in: ids } } } });
    await db.notificationOutbox.deleteMany({ where: { complaintId: { in: ids } } });
    await db.notification.deleteMany({ where: { href: { in: ids.map(id => `/admin/cases/${id}`) } } });
    await db.notification.deleteMany({ where: { userId: { in: userIds } } });
    await db.caseEvent.deleteMany({ where: { complaintId: { in: ids } } });
    await db.complaintSlaSnapshot.deleteMany({ where: { complaintId: { in: ids } } });
    await db.complaint.deleteMany({ where: { id: { in: ids } } });
    await db.slaPolicy.deleteMany({ where: { id: { in: policyIds } } });
    await db.auditLog.deleteMany({ where: { actorId: { in: userIds } } });
    await db.citizenProfile.deleteMany({ where: { userId: { in: userIds } } });
    await db.user.deleteMany({ where: { id: { in: userIds } } });
    await db.$disconnect();
  }
});
