import { testCookieName } from "./http-cookie";
import assert from "node:assert/strict";
import { createHash, randomBytes } from "node:crypto";
import { unlink } from "node:fs/promises";
import path from "node:path";
import { test } from "node:test";
import { PrismaClient } from "@prisma/client";
import { hashPassword } from "../src/lib/auth/password";
import { applyToVolunteer, reviewVolunteer } from "../src/lib/operations/volunteers";
import { addTaskNote, createTask, updateTaskStatus } from "../src/lib/operations/tasks";
import { createDepartment, createReferralDraft, updateDepartment, updateReferral } from "../src/lib/operations/referrals";
import { citizenResolution, transitionComplaint } from "../src/lib/operations/cases";
import { hasOutstandingInformationRequest, provideCaseInformation, reviewComplaint } from "../src/lib/operations/action-center";
import { canReadEvidence, evidenceDirectory, publishEvidence, uploadEvidence } from "../src/lib/operations/evidence";
import { OperationError } from "../src/lib/operations/common";

const base = process.env.AUTH_TEST_BASE_URL;

test("hybrid operations enforce approval, assignment, referrals, evidence and resolution", { skip: !base }, async () => {
  if (!base) return;
  if (!process.env.DATABASE_URL?.includes("auth-test.db")) throw new Error("Operations tests require auth-test.db.");
  const db = new PrismaClient();
  const suffix = randomBytes(6).toString("hex");
  const emails = ["admin", "owner", "other", "volunteer", "rejected"].map(prefix => `${prefix}-${suffix}@example.test`);
  const ids: string[] = [];
  const complaintIds: string[] = [];
  const departmentIds: string[] = [];
  const storedKeys: string[] = [];
  async function expectCode(work: () => Promise<unknown>, code: OperationError["code"]) {
    await assert.rejects(work, error => error instanceof OperationError && error.code === code);
  }
  async function webSession(userId: string) {
    const token = randomBytes(32).toString("hex");
    await db.session.create({ data: { userId, tokenHash: createHash("sha256").update(token).digest("hex"), expiresAt: new Date(Date.now() + 60_000) } });
    return `${testCookieName}=${token}`;
  }
  try {
    const passwordHash = await hashPassword(`test-secret-${suffix}`);
    const [admin, owner, other, volunteer, rejected] = await Promise.all(emails.map((email, index) => db.user.create({ data: { name: ["Admin", "Owner", "Other", "Volunteer", "Rejected"][index], email, passwordHash, role: index === 0 ? "ADMIN" : "CITIZEN" } })));
    ids.push(admin.id, owner.id, other.id, volunteer.id, rejected.id);
    const adminActor = { id: admin.id, role: admin.role };
    const ownerActor = { id: owner.id, role: owner.role };
    const volunteerActor = { id: volunteer.id, role: "VOLUNTEER" as const };
    const guided = await db.complaint.create({ data: { reference: `KFX-GUIDED-${suffix.toUpperCase()}`, title: "Guided review issue", category: "Other", description: "Needs further citizen details.", area: "East", userId: owner.id, status: "SUBMITTED" } });
    complaintIds.push(guided.id);
    const guidedAdminCookie = await webSession(admin.id), guidedOwnerCookie = await webSession(owner.id);
    assert.match(await (await fetch(`${base}/admin/cases/${guided.id}`, { headers: { Cookie: guidedAdminCookie } })).text(), /Review this complaint/);
    await expectCode(() => reviewComplaint(ownerActor, guided.id, "REQUEST_INFO", "Please share the exact street location."), "forbidden");
    await expectCode(() => reviewComplaint(adminActor, guided.id, "REQUEST_INFO", ""), "invalid");
    await reviewComplaint(adminActor, guided.id, "REQUEST_INFO", "Please share the exact street location.");
    assert.equal((await db.complaint.findUniqueOrThrow({ where: { id: guided.id } })).status, "BLOCKED");
    assert.equal(hasOutstandingInformationRequest("BLOCKED", [{ kind: "COMPLAINT_STATUS", summary: "BLOCKED: More information requested: street location" }]), true);
    assert.equal(hasOutstandingInformationRequest("BLOCKED", [{ kind: "COMPLAINT_STATUS", summary: "BLOCKED: awaiting equipment" }]), false);
    assert.match(await (await fetch(`${base}/track?ref=${guided.reference}`, { headers: { Cookie: guidedOwnerCookie } })).text(), /Send information to the team/);
    await expectCode(() => provideCaseInformation({ id: other.id, role: other.role }, guided.id, "Wrong person reply"), "forbidden");
    await provideCaseInformation(ownerActor, guided.id, "The issue is beside the community clinic on Main Road.");
    assert.equal(await db.caseEvent.count({ where: { complaintId: guided.id, kind: "CITIZEN_INFORMATION" } }), 1);
    await reviewComplaint(adminActor, guided.id, "VERIFY", "Location checked against the citizen reply.");
    assert.equal((await db.complaint.findUniqueOrThrow({ where: { id: guided.id } })).status, "VERIFIED");
    await expectCode(() => reviewComplaint(adminActor, guided.id, "REJECT", "Too late"), "conflict");
    await transitionComplaint(adminActor, guided.id, "BLOCKED", "Waiting for field equipment");
    await expectCode(() => provideCaseInformation(ownerActor, guided.id, "This should not be a citizen request."), "conflict");
    assert.doesNotMatch(await (await fetch(`${base}/track?ref=${guided.reference}`, { headers: { Cookie: guidedOwnerCookie } })).text(), /Send information to the team/);
    const rejectedGuided = await db.complaint.create({ data: { reference: `KFX-REVIEW-${suffix.toUpperCase()}`, title: "Review rejection issue", category: "Other", description: "Review found no actionable issue.", area: "East", userId: owner.id, status: "SUBMITTED" } });
    complaintIds.push(rejectedGuided.id);
    await reviewComplaint(adminActor, rejectedGuided.id, "REJECT", "The submitted report does not describe a civic issue.");
    assert.equal((await db.complaint.findUniqueOrThrow({ where: { id: rejectedGuided.id } })).status, "REJECTED");
    assert.equal((await fetch(`${base}/admin/cases/${guided.id}`, { headers: { Cookie: guidedOwnerCookie }, redirect: "manual" })).status, 307);
    const guidedPage = await (await fetch(`${base}/admin/cases/${guided.id}?action=team`, { headers: { Cookie: guidedAdminCookie } })).text();
    assert.match(guidedPage, /Case Action Center|Choose how to help/);
    assert.match(guidedPage, /Create action task/);
    assert.match(guidedPage, /Advanced Controls/);
    const application = await applyToVolunteer({ id: volunteer.id, role: "CITIZEN" }, { fullName: "Test Volunteer", district: "East", serviceArea: "Gulshan", contactPhone: "+923001234567", contactEmail: emails[3], skills: "Field documentation", availability: "Weekend mornings" });
    assert.equal(application.status, "PENDING");
    await expectCode(() => createTask({ id: owner.id, role: "CITIZEN" }, { complaintId: "x", type: "FIELD_VISIT", priority: "NORMAL", deadline: new Date(Date.now() + 86400000).toISOString(), instructions: "Inspect the site and record evidence" }), "forbidden");
    await reviewVolunteer(adminActor, application.id, "APPROVED", "Identity checked");
    assert.equal((await db.user.findUniqueOrThrow({ where: { id: volunteer.id } })).role, "VOLUNTEER");
    const rejectedApplication = await applyToVolunteer({ id: rejected.id, role: "CITIZEN" }, { fullName: "Rejected Candidate", district: "South", serviceArea: "Clifton", contactPhone: "+923001234568", contactEmail: emails[4], skills: "Community outreach", availability: "Weekday afternoons" });
    await reviewVolunteer(adminActor, rejectedApplication.id, "REJECTED", "Coverage not available");
    assert.equal((await db.user.findUniqueOrThrow({ where: { id: rejected.id } })).role, "CITIZEN");

    const complaint = await db.complaint.create({ data: { reference: `KFX-${suffix.toUpperCase()}`, title: "Test drainage complaint", category: "Water & drainage", description: "A blocked drain needs a field visit.", area: "Gulshan", userId: owner.id, status: "SUBMITTED" } });
    complaintIds.push(complaint.id);
    await db.caseEvent.create({ data: { complaintId: complaint.id, actorId: owner.id, kind: "SUBMITTED", summary: "Complaint submitted", visibility: "PUBLIC" } });
    await expectCode(() => transitionComplaint(adminActor, complaint.id, "RESOLVED", "Too soon"), "conflict");
    await transitionComplaint(adminActor, complaint.id, "UNDER_REVIEW", "Team review opened");
    await transitionComplaint(adminActor, complaint.id, "VERIFIED", "Field details verified");
    const task = await createTask(adminActor, { complaintId: complaint.id, assigneeId: volunteer.id, type: "FIELD_VISIT", priority: "HIGH", deadline: new Date(Date.now() + 86400000).toISOString(), instructions: "Visit the location and document the blocked drain." });
    assert.equal(task.status, "ASSIGNED");
    assert.equal((await db.complaint.findUniqueOrThrow({ where: { id: complaint.id } })).status, "ASSIGNED");
    await expectCode(() => updateTaskStatus({ id: other.id, role: "CITIZEN" }, task.id, "IN_PROGRESS"), "forbidden");
    await expectCode(() => updateTaskStatus({ id: rejected.id, role: "VOLUNTEER" }, task.id, "IN_PROGRESS"), "forbidden");
    await updateTaskStatus(volunteerActor, task.id, "IN_PROGRESS");
    await addTaskNote(volunteerActor, task.id, "The drain is blocked near the corner.");
    await updateTaskStatus(volunteerActor, task.id, "SUBMITTED_FOR_REVIEW", "Photos added");
    await expectCode(() => updateTaskStatus(volunteerActor, task.id, "COMPLETED"), "forbidden");
    await updateTaskStatus(adminActor, task.id, "COMPLETED", "Field work reviewed");
    assert.equal((await db.complaint.findUniqueOrThrow({ where: { id: complaint.id } })).status, "ASSIGNED");

    const department = await createDepartment(adminActor, { name: `Test Department ${suffix}`, jurisdiction: "District East", serviceAreas: "Drainage", contactDetails: "Official office" });
    departmentIds.push(department.id);
    await updateDepartment(adminActor, department.id, { jurisdiction: "District East and Central", serviceAreas: "Drainage and roads", active: true });
    assert.equal((await db.department.findUniqueOrThrow({ where: { id: department.id } })).jurisdiction, "District East and Central");
    const draft = await createReferralDraft(adminActor, complaint.id, department.id);
    assert.equal(draft.status, "DRAFT");
    assert.equal(draft.submittedAt, null);
    await expectCode(() => updateReferral(adminActor, draft.id, { status: "SUBMITTED" }), "invalid");
    assert.equal((await db.referral.findUniqueOrThrow({ where: { id: draft.id } })).status, "DRAFT");
    await updateReferral(adminActor, draft.id, { status: "SUBMITTED", submissionMethod: "Hand delivered", submittedAt: new Date().toISOString(), followUpAt: new Date(Date.now() + 86400000).toISOString() });
    assert.ok((await db.referral.findUniqueOrThrow({ where: { id: draft.id } })).submittedAt);
    await expectCode(() => updateReferral(adminActor, draft.id, { status: "ACTION_REPORTED" }), "invalid");
    await updateReferral(adminActor, draft.id, { status: "ACTION_REPORTED", response: "Department reported action on the drain." });
    assert.equal((await db.complaint.findUniqueOrThrow({ where: { id: complaint.id } })).status, "ASSIGNED");

    const png = new File([Buffer.from([137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 0])], "field.png", { type: "image/png" });
    const privateEvidence = await uploadEvidence(volunteerActor, { complaintId: complaint.id, taskId: task.id, stage: "BEFORE", file: png, note: "Before visit" });
    storedKeys.push(privateEvidence.storageKey);
    const evidenceWithAccess = await db.evidence.findUniqueOrThrow({ where: { id: privateEvidence.id }, include: { complaint: { select: { userId: true, cityId: true } }, task: { select: { assigneeId: true } } } });
    assert.equal(await canReadEvidence(ownerActor, evidenceWithAccess), false);
    assert.equal(await canReadEvidence({ id: other.id, role: "CITIZEN" }, evidenceWithAccess), false);
    assert.equal(await canReadEvidence(volunteerActor, evidenceWithAccess), true);
    assert.equal(await canReadEvidence(adminActor, evidenceWithAccess), true);
    const ownerCookie = await webSession(owner.id);
    const volunteerCookie = await webSession(volunteer.id);
    const otherCookie = await webSession(other.id);
    assert.equal((await fetch(`${base}/api/evidence/${privateEvidence.id}`, { headers: { Cookie: otherCookie } })).status, 404);
    assert.equal((await fetch(`${base}/api/evidence/${privateEvidence.id}`, { headers: { Cookie: ownerCookie } })).status, 404);
    assert.equal((await fetch(`${base}/api/evidence/${privateEvidence.id}`, { headers: { Cookie: volunteerCookie } })).status, 200);
    assert.equal((await fetch(`${base}/api/evidence/../../package.json`, { headers: { Cookie: volunteerCookie } })).status, 404);
    await publishEvidence(adminActor, privateEvidence.id);
    assert.equal((await fetch(`${base}/api/evidence/${privateEvidence.id}`, { headers: { Cookie: ownerCookie } })).status, 200);
    await transitionComplaint(adminActor, complaint.id, "IN_PROGRESS", "Field work underway");
    await expectCode(() => transitionComplaint(adminActor, complaint.id, "RESOLUTION_PROPOSED", "Ready"), "conflict");
    const afterEvidence = await uploadEvidence(adminActor, { complaintId: complaint.id, stage: "AFTER", visibility: "OWNER", file: png, note: "After work" });
    storedKeys.push(afterEvidence.storageKey);
    const volunteerOwned = await db.complaint.create({ data: { reference: `KFX-VOWN-${suffix.toUpperCase()}`, title: "Volunteer-owned citizen report", category: "Other", description: "A report submitted before volunteer approval.", area: "District East", userId: volunteer.id, status: "RESOLUTION_PROPOSED" } });
    complaintIds.push(volunteerOwned.id);
    const volunteerAfter = await uploadEvidence(adminActor, { complaintId: volunteerOwned.id, stage: "AFTER", visibility: "OWNER", file: png });
    storedKeys.push(volunteerAfter.storageKey);
    const volunteerDashboard = await fetch(`${base}/dashboard`, { headers: { Cookie: volunteerCookie }, redirect: "manual" });
    assert.equal(volunteerDashboard.status, 200);
    assert.match(await volunteerDashboard.text(), new RegExp(volunteerOwned.reference));
    assert.equal((await fetch(`${base}/report`, { headers: { Cookie: volunteerCookie }, redirect: "manual" })).status, 200);
    assert.equal((await fetch(`${base}/volunteer`, { headers: { Cookie: volunteerCookie }, redirect: "manual" })).status, 200);
    const volunteerTracking = await (await fetch(`${base}/track?ref=${volunteerOwned.reference}`, { headers: { Cookie: volunteerCookie } })).text();
    assert.match(volunteerTracking, /Review proposed resolution|Confirm resolution/);
    assert.match(volunteerTracking, /Volunteer-owned citizen report/);
    const unrelatedTracking = await (await fetch(`${base}/track?ref=${volunteerOwned.reference}`, { headers: { Cookie: otherCookie } })).text();
    assert.doesNotMatch(unrelatedTracking, /Volunteer-owned citizen report|Confirm resolution/);
    assert.equal((await fetch(`${base}/api/evidence/${volunteerAfter.id}`, { headers: { Cookie: volunteerCookie } })).status, 200);
    assert.equal((await fetch(`${base}/api/evidence/${volunteerAfter.id}`, { headers: { Cookie: otherCookie } })).status, 404);
    await expectCode(() => citizenResolution({ id: other.id, role: "CITIZEN" }, volunteerOwned.id, "CONFIRM"), "forbidden");
    await citizenResolution(volunteerActor, volunteerOwned.id, "CONFIRM");
    assert.equal((await db.complaint.findUniqueOrThrow({ where: { id: volunteerOwned.id } })).status, "RESOLVED");
    await transitionComplaint(adminActor, complaint.id, "RESOLUTION_PROPOSED", "Drain cleared; please review");
    await expectCode(() => citizenResolution({ id: other.id, role: "CITIZEN" }, complaint.id, "CONFIRM"), "forbidden");
    await citizenResolution(ownerActor, complaint.id, "DISPUTE", "Drain still overflows after rain.");
    assert.equal((await db.complaint.findUniqueOrThrow({ where: { id: complaint.id } })).status, "REOPENED");
    await transitionComplaint(adminActor, complaint.id, "VERIFIED", "Dispute checked in field");
    await transitionComplaint(adminActor, complaint.id, "RESOLUTION_PROPOSED", "Second visit complete; please review");
    await citizenResolution(ownerActor, complaint.id, "CONFIRM");
    assert.equal((await db.complaint.findUniqueOrThrow({ where: { id: complaint.id } })).status, "RESOLVED");
    await citizenResolution(ownerActor, complaint.id, "REOPEN", "The issue has returned after another rainfall.");
    assert.equal((await db.complaint.findUniqueOrThrow({ where: { id: complaint.id } })).status, "REOPENED");

    const legacy = await db.complaint.create({ data: { reference: `KFX-LEGACY-${suffix.toUpperCase()}`, title: "Legacy case", category: "Other", description: "No account is linked to this case.", area: "Central", status: "SUBMITTED" } });
    complaintIds.push(legacy.id);
    await transitionComplaint(adminActor, legacy.id, "UNDER_REVIEW", "Legacy review");
    await transitionComplaint(adminActor, legacy.id, "VERIFIED", "Verified field review");
    const legacyEvidence = await uploadEvidence(adminActor, { complaintId: legacy.id, stage: "AFTER", visibility: "OWNER", file: png });
    storedKeys.push(legacyEvidence.storageKey);
    await transitionComplaint(adminActor, legacy.id, "RESOLUTION_PROPOSED", "Field work reviewed");
    await transitionComplaint(adminActor, legacy.id, "RESOLVED", "Ownerless legacy case verified in field");
    assert.equal((await db.complaint.findUniqueOrThrow({ where: { id: legacy.id } })).status, "RESOLVED");
    assert.ok(await db.auditLog.count({ where: { actorId: admin.id } }));
    assert.ok(await db.notification.count({ where: { userId: owner.id } }));
  } finally {
    if (complaintIds.length) await db.complaint.deleteMany({ where: { id: { in: complaintIds } } });
    if (departmentIds.length) await db.department.deleteMany({ where: { id: { in: departmentIds } } });
    if (ids.length) await db.user.deleteMany({ where: { id: { in: ids } } });
    for (const key of storedKeys) await unlink(path.join(evidenceDirectory, key)).catch(() => undefined);
    await db.$disconnect();
  }
});
