import { testCookieName } from "./http-cookie";
import assert from "node:assert/strict";
import { createHash, randomBytes } from "node:crypto";
import { test } from "node:test";
import { PrismaClient } from "@prisma/client";
import { hashPassword } from "../src/lib/auth/password";
import { approximatePoint, nearbyReports, parseCoordinates, publicMapApprovalBlocker, PublicMapApprovalError, setPublicVisibility } from "../src/lib/geo";
import { answerAssistant, suggestCategory } from "../src/lib/assistant";
import { saveHelpArticle } from "../src/lib/help-articles";
import { answerSupportRequest, requestHumanSupport } from "../src/lib/support";

const base = process.env.AUTH_TEST_BASE_URL;
test("Phase 4 map privacy, location, duplicates, assistant and knowledge permissions", { skip: !base }, async () => {
  if (!base) return;
  if (!process.env.DATABASE_URL?.includes("auth-test.db")) throw new Error("Phase 4 integration tests require isolated auth-test.db");
  const db = new PrismaClient();
  const suffix = randomBytes(5).toString("hex");
  const userIds: string[] = [], complaintIds: string[] = [], articleIds: string[] = [], supportIds: string[] = [];
  const point = { latitude: 24.86321, longitude: 67.01123 };
  async function cookie(userId: string) { const token = randomBytes(32).toString("hex"); await db.session.create({ data: { userId, tokenHash: createHash("sha256").update(token).digest("hex"), expiresAt: new Date(Date.now() + 60000) } }); return `${testCookieName}=${token}`; }
  try {
    assert.equal(parseCoordinates("", ""), null);
    assert.deepEqual(parseCoordinates("24.86", "67.01"), { latitude: 24.86, longitude: 67.01 });
    assert.throws(() => parseCoordinates("91", "67"));
    assert.throws(() => parseCoordinates("24.86", ""));
    assert.deepEqual(approximatePoint(point), { latitude: 24.86, longitude: 67.01 });
    const passwordHash = await hashPassword(`phase4-${suffix}-password`);
    const [admin, owner, other] = await Promise.all(["ADMIN", "CITIZEN", "CITIZEN"].map((role, index) => db.user.create({ data: { name: `Phase4 ${index}`, email: `phase4-${index}-${suffix}@example.test`, passwordHash, role: role as "ADMIN" | "CITIZEN" } })));
    userIds.push(admin.id, owner.id, other.id);
    const legacy = await db.complaint.create({ data: { reference: `KFX-P4L-${suffix.toUpperCase()}`, title: "Legacy secret", category: "Other", description: "Legacy description should stay private", area: "Private street", status: "VERIFIED" } });
    complaintIds.push(legacy.id);
    assert.equal(publicMapApprovalBlocker(legacy), "location_required");
    await assert.rejects(() => setPublicVisibility({ id: admin.id, role: "ADMIN" }, legacy.id, true, "Public legacy", "District East"), (error: unknown) => error instanceof PublicMapApprovalError && error.code === "location_required");
    const stillPrivate = await db.complaint.findUniqueOrThrow({ where: { id: legacy.id } });
    assert.equal(stillPrivate.latitude, null); assert.equal(stillPrivate.longitude, null); assert.equal(stillPrivate.publicVisible, false);
    const privateCase = await db.complaint.create({ data: { reference: `KFX-P4P-${suffix.toUpperCase()}`, title: "Private home address 42", category: "Water & drainage", description: "Overflowing drain near a home address", area: "Private street", latitude: point.latitude, longitude: point.longitude, userId: owner.id, status: "VERIFIED" } });
    complaintIds.push(privateCase.id);
    const publicCase = await db.complaint.create({ data: { reference: `KFX-P4V-${suffix.toUpperCase()}`, title: "Private title with house number 42", category: "Water & drainage", description: "Overflowing drainage near a public road", area: "Sensitive street number 42", district: "East", latitude: point.latitude, longitude: point.longitude, userId: owner.id, status: "VERIFIED" } });
    complaintIds.push(publicCase.id);
    assert.equal(publicMapApprovalBlocker(publicCase), null);
    await assert.rejects(() => setPublicVisibility({ id: other.id, role: "CITIZEN" }, publicCase.id, true, "Public drain issue", "Gulshan"));
    await setPublicVisibility({ id: admin.id, role: "ADMIN" }, publicCase.id, true, "Public drain issue", "Gulshan");
    const map = await fetch(`${base}/api/map`);
    assert.equal(map.status, 200);
    const raw = await map.text();
    assert.match(raw, /Public drain issue/);
    assert.doesNotMatch(raw, /Private title|house number|Sensitive street|Legacy secret|Private home address|Overflowing drainage|67\.01123/);
    const data = JSON.parse(raw) as { items: { id: string; latitude: number; longitude: number }[] };
    const shown = data.items.find(item => item.id === publicCase.id);
    assert.deepEqual([shown?.latitude, shown?.longitude], [24.86, 67.01]);
    assert.equal(data.items.some(item => item.id === privateCase.id || item.id === legacy.id), false);
    assert.equal((await fetch(`${base}/api/map`, { headers: { "If-None-Match": map.headers.get("etag")! } })).status, 304);
    assert.equal((await fetch(`${base}/api/map?district=East`)).status, 200);
    const nearby = await nearbyReports(point, "Water & drainage", "Drain overflowing on road");
    assert.equal(nearby.some(item => item.id === publicCase.id), true);
    assert.equal(nearby.some(item => item.id === privateCase.id), false);
    assert.ok(nearby.every(item => !JSON.stringify(item).includes("67.01123")));
    const ownerCookie = await cookie(owner.id), otherCookie = await cookie(other.id);
    assert.equal((await fetch(`${base}/api/nearby?latitude=${point.latitude}&longitude=${point.longitude}&category=Water%20%26%20drainage`, { headers: { Cookie: ownerCookie } })).status, 200);
    assert.equal((await fetch(`${base}/api/nearby?latitude=91&longitude=67&category=Water%20%26%20drainage`, { headers: { Cookie: ownerCookie } })).status, 400);
    assert.equal((await fetch(`${base}/api/nearby?latitude=${point.latitude}&longitude=${point.longitude}&category=Water%20%26%20drainage`)).status, 401);
    const own = await answerAssistant({ id: owner.id, role: "CITIZEN" }, `What is ${publicCase.reference}?`, "en");
    assert.match(own.text, /Current status: VERIFIED/);
    const unauthorized = await answerAssistant({ id: other.id, role: "CITIZEN" }, `What is ${publicCase.reference}?`, "en");
    assert.doesNotMatch(unauthorized.text, /VERIFIED|Private title|house number/);
    const unauthorizedHttp = await fetch(`${base}/api/assistant`, { method: "POST", headers: { Cookie: otherCookie, "Content-Type": "application/json" }, body: JSON.stringify({ message: `What is ${publicCase.reference}?`, language: "en" }) });
    assert.equal(unauthorizedHttp.status, 200);
    assert.doesNotMatch(await unauthorizedHttp.text(), /VERIFIED|Private title|house number/);
    const publicReply = await answerAssistant(null, `What is ${publicCase.reference}?`, "en");
    assert.doesNotMatch(publicReply.text, /VERIFIED|Private title/);
    const fallback = await answerAssistant(null, "How do I report a pothole?", "ur-Latn");
    assert.equal(fallback.source, "local");
    assert.equal(await suggestCategory("A blocked drain is overflowing"), "Water & drainage");
    await assert.rejects(() => saveHelpArticle({ id: other.id, role: "CITIZEN" }, { title: "Fake contact", category: "Support", language: "en", content: "Do not publish this unverified information.", published: true }));
    const article = await saveHelpArticle({ id: admin.id, role: "ADMIN" }, { title: "Reporting guidance", category: "Reporting", language: "en", content: "Describe your issue and include a public landmark where safe.", published: false });
    articleIds.push(article.id);
    assert.equal((await answerAssistant(null, "Reporting guidance", "en")).articles?.length, 0);
    await saveHelpArticle({ id: admin.id, role: "ADMIN" }, { id: article.id, title: article.title, category: article.category, language: "en", content: article.content, published: true });
    assert.equal((await answerAssistant(null, "Reporting guidance", "en")).articles?.[0]?.title, "Reporting guidance");
    await assert.rejects(() => requestHumanSupport({ id: admin.id, role: "ADMIN" }, "Please help with my report", "en"));
    const support = await requestHumanSupport({ id: owner.id, role: "CITIZEN" }, "Please help explain my report next steps", "en");
    supportIds.push(support.id);
    await assert.rejects(() => answerSupportRequest({ id: other.id, role: "CITIZEN" }, support.id, "Here is a response from staff"));
    await answerSupportRequest({ id: admin.id, role: "ADMIN" }, support.id, "We received your question and will review the report.");
    assert.equal((await db.supportRequest.findUniqueOrThrow({ where: { id: support.id } })).status, "ANSWERED");
    assert.ok(await db.notification.count({ where: { userId: owner.id, title: "Behtar Pakistan support replied" } }));
    await setPublicVisibility({ id: admin.id, role: "ADMIN" }, publicCase.id, false);
    assert.equal((await fetch(`${base}/api/map`)).status, 200);
    assert.equal((await fetch(`${base}/api/map`).then(response => response.json()) as { items: { id: string }[] }).items.some(item => item.id === publicCase.id), false);
  } finally {
    if (supportIds.length) await db.supportRequest.deleteMany({ where: { id: { in: supportIds } } });
    if (complaintIds.length) await db.complaint.deleteMany({ where: { id: { in: complaintIds } } });
    if (articleIds.length) await db.helpArticle.deleteMany({ where: { id: { in: articleIds } } });
    if (userIds.length) await db.user.deleteMany({ where: { id: { in: userIds } } });
    await db.$disconnect();
  }
});
