import { testCookieName } from "./http-cookie";
import assert from "node:assert/strict";
import { createHash, randomBytes } from "node:crypto";
import { mkdir, unlink, writeFile } from "node:fs/promises";
import path from "node:path";
import { test } from "node:test";
import { PrismaClient } from "@prisma/client";
import { hashPassword } from "../src/lib/auth/password";
import { getPublicProject, listPublicProjects } from "../src/lib/public-projects";
import { setNgoEvidencePublic, setNgoMilestonePublic, setNgoProjectPublic } from "../src/lib/operations/ngos";
import { privateStoragePath } from "../src/lib/private-storage";

const base = process.env.AUTH_TEST_BASE_URL;
test("only reviewed project content is public and publication is admin-only", { skip: !base }, async () => {
  if (!base || !process.env.DATABASE_URL?.includes("auth-test.db")) throw new Error("Use isolated auth-test.db");
  const db = new PrismaClient(), suffix = randomBytes(5).toString("hex");
  let ngoId = "", projectId = "", complaintId = "", milestoneId = "", evidenceId = "";
  let fixturePath = "";
  const users: string[] = [];
  try {
    const passwordHash = await hashPassword(`project-${suffix}-password`);
    const admin = await db.user.create({ data: { name: "Project admin", email: `project-admin-${suffix}@example.test`, passwordHash, role: "ADMIN" } });
    const citizen = await db.user.create({ data: { name: "Project citizen", email: `project-citizen-${suffix}@example.test`, passwordHash, role: "CITIZEN" } });
    users.push(admin.id, citizen.id);
    const actor = { id: admin.id, role: admin.role }, outsider = { id: citizen.id, role: citizen.role };
    const ngo = await db.partnerNgo.create({ data: { name: `Project Group ${suffix}`, contactPerson: "Private contact", contactEmail: `secret-${suffix}@example.test`, serviceAreas: "East", expertise: "Field work", status: "ACTIVE", verifiedAt: new Date(), verifiedById: admin.id, agreementNote: "Reviewed signed agreement" } }); ngoId = ngo.id;
    const complaint = await db.complaint.create({ data: { reference: `KFX-PROJECT-${suffix.toUpperCase()}`, title: "PRIVATE CASE TITLE", description: "PRIVATE CASE DESCRIPTION", category: "Roads", area: "Private address", status: "VERIFIED", publicVisible: false } }); complaintId = complaint.id;
    const project = await db.ngoProject.create({ data: { ngoId, complaintId, title: `Public work ${suffix}`, description: "PRIVATE PROJECT DESCRIPTION", status: "ACTIVE", createdById: admin.id } }); projectId = project.id;
    const milestone = await db.ngoMilestone.create({ data: { projectId, title: "Drain work checked", outcome: "Work was documented on site.", completedAt: new Date() } }); milestoneId = milestone.id;
    const evidence = await db.evidence.create({ data: { complaintId, ngoProjectId: projectId, uploaderId: admin.id, stage: "AFTER", visibility: "INTERNAL", storageKey: `${randomBytes(20).toString("hex")}.png`, originalName: "private.png", mimeType: "image/png", size: 12, note: "PRIVATE FIELD NOTE" } }); evidenceId = evidence.id;
    assert.equal(await getPublicProject(projectId), null);
    assert.equal((await fetch(`${base}/projects/${projectId}`)).status, 404);
    assert.equal((await fetch(`${base}/api/projects/evidence/${evidenceId}`)).status, 404);
    await assert.rejects(() => setNgoProjectPublic(outsider, projectId, true, "Reviewed project progress is documented here."));
    await assert.rejects(() => setNgoProjectPublic(actor, projectId, true, `Email secret-${suffix}@example.test for details`));
    await setNgoProjectPublic(actor, projectId, true, "Reviewed project progress is documented here.");
    assert.equal((await listPublicProjects()).some(item => item.id === projectId), true);
    let publicRecord = await getPublicProject(projectId);
    assert.equal(publicRecord?.complaint, null);
    assert.equal(publicRecord?.milestones.length, 0);
    assert.equal(publicRecord?.evidence.length, 0);
    await assert.rejects(() => setNgoMilestonePublic(outsider, milestoneId, true));
    await setNgoMilestonePublic(actor, milestoneId, true);
    await assert.rejects(() => setNgoEvidencePublic(actor, evidenceId, true, false));
    await assert.rejects(() => setNgoEvidencePublic(outsider, evidenceId, true, true));
    await setNgoEvidencePublic(actor, evidenceId, true, true);
    fixturePath = privateStoragePath(evidence.storageKey);
    await mkdir(path.dirname(fixturePath), { recursive: true });
    await writeFile(fixturePath, Buffer.from("89504e470d0a1a0a0000000d49484452", "hex"), { flag: "wx" });
    assert.equal((await fetch(`${base}/api/projects/evidence/${evidenceId}`)).status, 200);
    publicRecord = await getPublicProject(projectId);
    assert.equal(publicRecord?.milestones.length, 1);
    assert.equal(publicRecord?.evidence.length, 1);
    const html = await (await fetch(`${base}/projects/${projectId}`)).text();
    assert.match(html, /Reviewed project progress|Work was documented/);
    assert.doesNotMatch(html, /PRIVATE CASE TITLE|PRIVATE CASE DESCRIPTION|PRIVATE PROJECT DESCRIPTION|PRIVATE FIELD NOTE|secret-.*@example.test/);
    await db.complaint.update({ where: { id: complaintId }, data: { publicVisible: true, publicTitle: "Public street report", publicArea: "District East" } });
    assert.equal((await getPublicProject(projectId))?.complaint?.publicTitle, "Public street report");
    await setNgoEvidencePublic(actor, evidenceId, false, false);
    assert.equal((await fetch(`${base}/api/projects/evidence/${evidenceId}`)).status, 404);
    await setNgoProjectPublic(actor, projectId, false);
    assert.equal((await fetch(`${base}/projects/${projectId}`)).status, 404);
    const token = randomBytes(32).toString("hex");
    await db.session.create({ data: { userId: citizen.id, tokenHash: createHash("sha256").update(token).digest("hex"), expiresAt: new Date(Date.now() + 60_000) } });
    assert.equal((await fetch(`${base}/admin/ngos/${ngoId}`, { headers: { Cookie: `${testCookieName}=${token}` }, redirect: "manual" })).status, 307);
  } finally {
    if (fixturePath) await unlink(fixturePath).catch(() => undefined);
    if (evidenceId) await db.evidence.delete({ where: { id: evidenceId } });
    if (milestoneId) await db.ngoMilestone.delete({ where: { id: milestoneId } });
    if (projectId) await db.ngoProject.delete({ where: { id: projectId } });
    if (ngoId) await db.partnerNgo.delete({ where: { id: ngoId } });
    if (complaintId) await db.complaint.delete({ where: { id: complaintId } });
    await db.auditLog.deleteMany({ where: { actorId: { in: users } } });
    await db.user.deleteMany({ where: { id: { in: users } } });
    await db.$disconnect();
  }
});
