import { prisma } from "@/lib/prisma";
import { requireRole } from "@/lib/auth/session";
import { recordExpenseAction } from "@/app/actions/donations";
import { AdminNav, ErrorNotice } from "@/components/operations";
import { DonationAdminNav } from "@/components/donation-admin-nav";

export const dynamic = "force-dynamic";
export default async function ExpensesPage({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  await requireRole(["ADMIN"]);
  const [{ error }, campaigns, expenses] = await Promise.all([searchParams, prisma.donationCampaign.findMany({ select: { id: true, title: true }, orderBy: { title: "asc" } }), prisma.donationExpense.findMany({ orderBy: { spentAt: "desc" }, take: 100, include: { campaign: { select: { title: true } }, recordedBy: { select: { name: true } } } })]);
  return <section className="inner-page"><div className="page-shell"><p className="section-kicker">Documented spending</p><h1 className="page-heading mt-3">Donation expenses</h1><p className="page-subtitle">Record real spending with supporting documentation. Only published expense entries appear on the public transparency page.</p><AdminNav /><DonationAdminNav /><ErrorNotice error={error} /><form action={recordExpenseAction} className="surface-card mt-8 grid gap-4 sm:grid-cols-2"><h2 className="text-xl font-bold sm:col-span-2">Record expense</h2><div><label className="field-label" htmlFor="expense-campaign">Fund</label><select id="expense-campaign" name="campaignId" className="field-input"><option value="">General fund</option>{campaigns.map(item => <option key={item.id} value={item.id}>{item.title}</option>)}</select></div><div><label className="field-label" htmlFor="expense-amount">Amount (PKR)</label><input id="expense-amount" name="amount" type="number" min={100} max={1000000} className="field-input" required /></div><div><label className="field-label" htmlFor="expense-purpose">Purpose</label><input id="expense-purpose" name="purpose" className="field-input" minLength={5} maxLength={200} required /></div><div><label className="field-label" htmlFor="expense-date">Date spent</label><input id="expense-date" name="spentAt" type="date" className="field-input" required /></div><div className="sm:col-span-2"><label className="field-label" htmlFor="expense-documentation">Documentation summary / record reference</label><textarea id="expense-documentation" name="documentation" className="field-input min-h-24" minLength={10} maxLength={1000} required /></div><label className="flex items-center gap-2 text-sm sm:col-span-2"><input type="checkbox" name="publish" /> Publish this checked documentation on the transparency page</label><button type="submit" className="btn-dark w-fit cursor-pointer">Record expense</button></form><div className="mt-7 space-y-4">{expenses.map(item => <div key={item.id} className="surface-card"><div className="flex flex-wrap justify-between gap-3"><h2 className="font-bold">{item.purpose}</h2><strong>PKR {item.amountPkr.toLocaleString("en-PK")}</strong></div><p className="mt-2 text-xs text-slate-500">{item.campaign?.title ?? "General fund"} · {item.spentAt.toLocaleDateString("en-PK")} · {item.recordedBy.name} · {item.publishedAt ? "Published" : "Private draft"}</p><p className="mt-3 whitespace-pre-wrap text-sm text-slate-700">{item.documentation}</p></div>)}</div></div></section>;
}
