import Link from "next/link";
import { requireRole } from "@/lib/auth/session";
import { prisma } from "@/lib/prisma";
import { AdminNav } from "@/components/operations";
import { reviewCaseLinkAction } from "@/app/actions/duplicates";
import { detectorHistoryState } from "@/lib/duplicates";
import { formatPakistanDateTime } from "@/lib/pakistan-time";

export const dynamic = "force-dynamic";
export default async function DuplicateReviewPage({ searchParams }: { searchParams: Promise<{ saved?: string; error?: string }> }) {
  await requireRole(["ADMIN"], "/admin/duplicates");
  const [query, links, recentReports] = await Promise.all([searchParams, prisma.caseLink.findMany({
    orderBy: { createdAt: "desc" }, take: 100,
    include: { sourceComplaint: { select: { id: true, reference: true, title: true, category: true, district: true, area: true, status: true } }, targetComplaint: { select: { id: true, reference: true, title: true, category: true, district: true, area: true, status: true } } },
  }), prisma.complaint.findMany({ orderBy: { createdAt: "desc" }, take: 50, select: { id: true, reference: true, createdAt: true, category: true, status: true, duplicateSuggestions: { select: { status: true } } } })]);
  const runs = recentReports.length ? await prisma.auditLog.findMany({ where: { action: "DUPLICATE_DETECTION_RUN", targetType: "Complaint", targetId: { in: recentReports.map(report => report.id) } }, orderBy: { createdAt: "desc" }, select: { targetId: true, createdAt: true, details: true } }) : [];
  const latestRun = new Map<string, (typeof runs)[number]>();
  for (const run of runs) if (!latestRun.has(run.targetId)) latestRun.set(run.targetId, run);
  return <section className="inner-page"><div className="page-shell"><p className="section-kicker">Admin review</p><h1 className="page-heading mt-3">Related case suggestions</h1><p className="page-subtitle">A suggestion is never an automatic merge. Every report keeps its own citizen, timeline, SLA, tasks, evidence, resolution confirmation and publication gates. Resolved public cases can appear as historical citizen suggestions, but are not eligible for a new admin link.</p><AdminNav />
    <section className="surface-card mt-5 text-sm" aria-labelledby="detector-history"><h2 id="detector-history" className="font-bold">Submission detector history</h2><p className="mt-1 text-slate-600">Latest 50 reports. A run is recorded when submission succeeds. Older reports may show Never ran. Zero candidates means no approved active partner exists or active cases were not sufficiently similar.</p><div className="mt-4 space-y-2">{recentReports.map(report => { const run = latestRun.get(report.id); let details: { reason?: string; candidateCount?: number } | null = null; if (run) { try { details = JSON.parse(run.details ?? "{}"); } catch { details = {}; } } const state = detectorHistoryState(details, report.duplicateSuggestions.map(link => link.status)); return <div key={report.id} className="flex flex-wrap items-center justify-between gap-2 rounded-xl border border-slate-200 p-3"><div><Link href={`/admin/cases/${report.id}`} className="font-bold text-emerald-800 underline">{report.reference}</Link><span className="ml-2 text-slate-500">{report.category} · {report.status.replaceAll("_", " ")}</span><p className="text-xs text-slate-600">Submitted {formatPakistanDateTime(report.createdAt)} · Detector {run ? formatPakistanDateTime(run.createdAt) : "never recorded"} · {details?.candidateCount ?? 0} candidate(s)</p></div><span className="rounded-full bg-slate-100 px-3 py-1 font-semibold">{state}</span></div>; })}{!recentReports.length && <p>No reports have been submitted.</p>}</div></section>
    {query.saved && <p role="status" className="mt-5 text-emerald-800">Case relationship saved.</p>}{query.error && <p role="alert" className="form-error mt-5">Could not save this decision. Check the reason and case state.</p>}
    <div className="mt-7 space-y-4">{links.map(link => <article key={link.id} className="surface-card"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="text-lg font-bold">{link.sourceComplaint.reference} → {link.targetComplaint.reference}</h2><span className="text-xs font-bold text-emerald-800">{link.status} · {link.score}/100</span></div><p className="mt-1 text-xs text-slate-500">Suggested {formatPakistanDateTime(link.createdAt)} · Matching used approved public category, district, approximate area and public-title similarity. Admin review is required.</p><div className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><div><Link href={`/admin/cases/${link.sourceComplaint.id}`} className="font-bold text-emerald-700 underline">New report: {link.sourceComplaint.title}</Link><p>{link.sourceComplaint.category} · {link.sourceComplaint.district}, {link.sourceComplaint.area} · {link.sourceComplaint.status}</p></div><div><Link href={`/admin/cases/${link.targetComplaint.id}`} className="font-bold text-emerald-700 underline">Possible related report: {link.targetComplaint.title}</Link><p>{link.targetComplaint.category} · {link.targetComplaint.district}, {link.targetComplaint.area} · {link.targetComplaint.status}</p></div></div>{link.reason && <p className="mt-3 text-sm text-slate-600">Review reason: {link.reason}</p>}
      <form action={reviewCaseLinkAction} className="mt-4 flex flex-wrap items-end gap-3"><input type="hidden" name="linkId" value={link.id} /><label className="min-w-52 flex-1"><span className="field-label">Reason for decision</span><input name="reason" className="field-input" minLength={5} maxLength={500} required /></label>{link.status === "LINKED" ? <button name="decision" value="UNLINKED" className="min-h-12 rounded-xl border border-amber-500 px-4 text-sm font-bold">Unlink / correct</button> : <>{![link.sourceComplaint.status, link.targetComplaint.status].some(status => ["RESOLVED", "REJECTED"].includes(status)) ? <button name="decision" value="LINKED" className="btn-dark">Link as related</button> : <span className="text-xs text-slate-600">Link unavailable: one case is resolved or rejected.</span>}<button name="decision" value="REJECTED" className="min-h-12 rounded-xl border px-4 text-sm font-bold">Not the same issue</button></>}</form></article>)}{!links.length && <div className="surface-card text-sm text-slate-600">No candidate links have been recorded.</div>}</div>
  </div></section>;
}
