import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { listPublicProjects } from "@/lib/public-projects";
import { listPublishedStories } from "@/lib/completed-work-public";
import { activePublicCities, selectedPublicCity } from "@/lib/public-cities";
import { notFound } from "next/navigation";

export const metadata: Metadata = { title: "Community projects and completed work" };
export const dynamic = "force-dynamic";

export default async function ProjectsPage({ searchParams }: { searchParams: Promise<{ city?: string }> }) {
  const [{ city: slug }, cities] = await Promise.all([searchParams, activePublicCities()]);
  const city = selectedPublicCity(slug, cities);
  if (city === undefined) notFound();
  const [projects, stories] = await Promise.all([listPublicProjects(city?.id), listPublishedStories(city?.id)]);
  const linkedCases = new Set(stories.map(item => item.complaintId));
  const remainingProjects = projects.filter(item => !item.complaintId || !linkedCases.has(item.complaintId));
  return <section className="inner-page"><div className="page-shell"><p className="section-kicker">Documented work</p><h1 className="page-heading mt-3">Our Projects</h1><p className="page-subtitle">Completed work appears here only after resolution verification and approval of the public summary and real before and after photos. Donations do not change complaint priority.</p><nav aria-label="Filter projects by city" className="mt-5 flex flex-wrap gap-2"><Link href="/projects" aria-current={!city ? "page" : undefined} className={`rounded-full border px-4 py-2 text-sm font-bold focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-emerald-700 ${!city ? "border-emerald-800 bg-emerald-800 text-white" : "border-emerald-200 bg-white text-emerald-900 hover:bg-emerald-50"}`}>Nationwide and reviewed legacy</Link>{cities.map(item => <Link key={item.id} href={`/projects?city=${encodeURIComponent(item.slug)}`} aria-current={city?.id === item.id ? "page" : undefined} className={`rounded-full border px-4 py-2 text-sm font-bold focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-emerald-700 ${city?.id === item.id ? "border-emerald-800 bg-emerald-800 text-white" : "border-emerald-200 bg-white text-emerald-900 hover:bg-emerald-50"}`}>{item.name}</Link>)}</nav>
    <section className="mt-9"><h2 className="text-2xl font-bold">Before &amp; After</h2><div className="mt-5 grid gap-6 md:grid-cols-2 xl:grid-cols-3">{stories.map(item => <article key={item.id} className="surface-card overflow-hidden p-0"><div className="grid grid-cols-2"><div className="relative aspect-[4/3] bg-slate-100"><Image unoptimized src={`/api/projects/completed/${item.id}/media/before`} alt={`Before: ${item.complaint.publicTitle}`} fill className="object-cover" /><span className="absolute bottom-2 left-2 rounded-full bg-slate-900/85 px-2 py-1 text-xs font-bold text-white">Before</span></div><div className="relative aspect-[4/3] bg-slate-100"><Image unoptimized src={`/api/projects/completed/${item.id}/media/after`} alt={`After: ${item.complaint.publicTitle}`} fill className="object-cover" /><span className="absolute bottom-2 left-2 rounded-full bg-emerald-800/90 px-2 py-1 text-xs font-bold text-white">After</span></div></div><div className="p-5"><p className="text-xs font-bold uppercase text-emerald-700">Verified resolved work</p><h3 className="mt-2 text-xl font-bold">{item.complaint.publicTitle}</h3><p className="mt-2 text-sm text-slate-600">{item.complaint.reference} · {item.complaint.category}</p><p className="mt-1 text-sm text-slate-600">{item.complaint.district}, {item.complaint.publicArea}</p><p className="mt-2 text-xs text-slate-500">Completed {item.completedAt?.toLocaleDateString("en-PK")}{item.complaint.ngoProjects[0] ? ` · ${item.complaint.ngoProjects[0].ngo.name}` : ""}</p><Link href={`/projects/completed/${item.id}`} className="mt-4 inline-block rounded-lg bg-emerald-800 px-4 py-2 text-sm font-bold text-white">View details</Link></div></article>)}{!stories.length && <p className="surface-card text-sm text-slate-600">No completed work has passed all public review checks yet.</p>}</div></section>
    <section className="mt-10"><h2 className="text-2xl font-bold">Community projects</h2><div className="mt-5 grid gap-5 md:grid-cols-2">{remainingProjects.map(item => <Link key={item.id} href={`/projects/${item.id}`} className="surface-card hover:border-emerald-300"><p className="text-xs font-bold uppercase text-emerald-700">{item.status} · {item.ngo.name}</p><h3 className="mt-2 text-xl font-bold">{item.title}</h3><p className="mt-2 text-sm text-slate-600">{item.publicSummary}</p><p className="mt-3 text-xs text-slate-500">{item.milestones.length} approved outcomes · Updated {item.updatedAt.toLocaleDateString("en-PK")}</p></Link>)}{!remainingProjects.length && <p className="surface-card text-sm text-slate-600">No additional public project updates.</p>}</div></section>
  </div></section>;
}
