import { WalletMethod } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { requireRole } from "@/lib/auth/session";
import { walletNames } from "@/lib/donations";
import { configureWalletAction } from "@/app/actions/donations";
import { AdminNav, ErrorNotice } from "@/components/operations";
import { DonationAdminNav } from "@/components/donation-admin-nav";

export const dynamic = "force-dynamic";
export default async function WalletSettingsPage({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  await requireRole(["ADMIN"]);
  const [{ error }, wallets] = await Promise.all([searchParams, prisma.walletAccount.findMany()]);
  const byMethod = new Map(wallets.map(item => [item.method, item]));
  return <section className="inner-page"><div className="page-shell"><p className="section-kicker">Payment setup</p><h1 className="page-heading mt-3">Wallet accounts</h1><p className="page-subtitle">Configure each wallet separately. The project owner supplied a receiving number, but its wallet association and account title must be checked before any method is enabled publicly.</p>{process.env.DONATION_CANDIDATE_NUMBER && <p className="mt-4 rounded-xl bg-amber-50 p-4 text-sm text-amber-900">Owner-supplied, unassigned candidate number: <strong>{process.env.DONATION_CANDIDATE_NUMBER}</strong>. Confirm its wallet and account title before enabling it.</p>}<AdminNav /><DonationAdminNav /><ErrorNotice error={error} /><div className="mt-8 grid gap-5 sm:grid-cols-2">{Object.values(WalletMethod).map(method => { const item = byMethod.get(method); return <form key={method} action={configureWalletAction} className="surface-card space-y-4"><input type="hidden" name="method" value={method} /><h2 className="text-xl font-bold">{walletNames[method]}</h2><p className="text-xs text-slate-500">{item?.enabled && item.verifiedAt ? `Enabled · verified ${item.verifiedAt.toLocaleDateString("en-PK")}` : "Not publicly enabled"}</p><div><label className="field-label" htmlFor={`${method}-number`}>Actual receiving number / account</label><input id={`${method}-number`} name="accountNumber" defaultValue={item?.accountNumber ?? ""} className="field-input" minLength={10} maxLength={34} required /></div><div><label className="field-label" htmlFor={`${method}-title`}>Account title</label><input id={`${method}-title`} name="accountTitle" defaultValue={item?.accountTitle ?? ""} className="field-input" minLength={3} maxLength={100} required /></div><div><label className="field-label" htmlFor={`${method}-instructions`}>Method-specific payment instructions</label><textarea id={`${method}-instructions`} name="instructions" defaultValue={item?.instructions ?? ""} className="field-input min-h-28" minLength={15} maxLength={1000} required /></div><div><label className="field-label" htmlFor={`${method}-enabled`}>Public status</label><select id={`${method}-enabled`} name="enabled" defaultValue={item?.enabled ? "1" : "0"} className="field-input"><option value="0">Disabled</option><option value="1">Enabled after verification</option></select></div><label className="flex items-start gap-2 text-xs text-slate-700"><input name="confirmed" type="checkbox" className="mt-1" /> I independently confirmed this wallet, account title, number and instructions with the project owner.</label><button type="submit" className="btn-dark cursor-pointer">Save {walletNames[method]}</button></form>; })}</div></div></section>;
}
