
import { brand } from "@/lib/brand";
import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { formatPakistanDateTime } from "@/lib/pakistan-time";
import { requireRole } from "@/lib/auth/session";
import { caseNoteAction, complaintStatusAction, createReferralDraftAction, createTaskAction, guidedReviewAction, updateReferralAction, uploadEvidenceAction } from "@/app/actions/operations";
import { PublicMapApproval } from "@/components/public-map-approval";
import { citizenProgress, hasOutstandingInformationRequest } from "@/lib/operations/action-center";
import { label, nextComplaintStatuses, priorities, taskTypes } from "@/lib/workflow";
import { AdminNav, ErrorNotice, EvidenceCards, StatusBadge, Timeline } from "@/components/operations";
import { AdvancedCaseTools } from "@/components/advanced-case-tools";
import { TaskDeadlineField } from "@/components/task-deadline-field";

export const metadata: Metadata = { title: "Case Action Center" };
export const dynamic = "force-dynamic";

const actionChoices = [
  ["government", "Forward to department", "Prepare a referral, then record the real submission."],
  ["team", "Assign volunteer / team", "Give a verified team member a clear task and deadline."],
  ["ngo", "Coordinate partner NGO", "Record who will coordinate and what they will do."],
  ["direct", "Record action taken", "Update progress and add field evidence."],
] as const;

export default async function AdminCasePage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ error?: string; action?: string }> }) {
  await requireRole(["ADMIN"]);
  const [{ id }, query] = await Promise.all([params, searchParams]);
  const [complaint, departments, assignees] = await Promise.all([
    prisma.complaint.findUnique({ where: { id }, include: { user: { select: { name: true, email: true } }, tasks: { orderBy: { createdAt: "desc" }, include: { assignee: { select: { name: true } } } }, referrals: { orderBy: { createdAt: "desc" }, include: { department: { select: { name: true } } } }, evidence: { orderBy: { createdAt: "desc" } }, events: { orderBy: { createdAt: "desc" }, include: { actor: { select: { name: true } } } } } }),
    prisma.department.findMany({ where: { active: true }, orderBy: { name: "asc" } }),
    prisma.user.findMany({ where: { OR: [{ role: "ADMIN" }, { role: "VOLUNTEER", volunteerApplication: { is: { status: "APPROVED" } } }] }, select: { id: true, name: true, role: true }, orderBy: { name: "asc" } }),
  ]);
  if (!complaint) notFound();
  const audits = await prisma.auditLog.findMany({ where: { OR: [
    { targetType: "Complaint", targetId: id },
    { targetType: "Task", targetId: { in: complaint.tasks.map(item => item.id) } },
    { targetType: "Referral", targetId: { in: complaint.referrals.map(item => item.id) } },
    { targetType: "Evidence", targetId: { in: complaint.evidence.map(item => item.id) } },
  ] }, orderBy: { createdAt: "desc" }, include: { actor: { select: { name: true } } } });
  const casePath = `/admin/cases/${complaint.id}`;
  const informationRequested = hasOutstandingInformationRequest(complaint.status, complaint.events);
  const wasVerified = complaint.events.some(item => item.kind === "VERIFIED");
  const reviewStage = ["SUBMITTED", "UNDER_REVIEW", "REOPENED"].includes(complaint.status) || (complaint.status === "BLOCKED" && (informationRequested || !wasVerified));
  const actionStage = ["VERIFIED", "ASSIGNED", "IN_PROGRESS"].includes(complaint.status) || (complaint.status === "BLOCKED" && wasVerified && !informationRequested);
  const afterShared = complaint.evidence.some(item => item.stage === "AFTER" && item.visibility === "OWNER");
  const openTasks = complaint.tasks.filter(item => !["COMPLETED", "CANCELLED"].includes(item.status));
  const allowed = nextComplaintStatuses(complaint.status).filter(status => status !== "RESOLVED" || !complaint.userId);
  const selectedReview = ["verify", "information", "reject"].includes(query.action ?? "")
    && (query.action !== "information" || ["SUBMITTED", "UNDER_REVIEW"].includes(complaint.status))
    && (query.action !== "reject" || complaint.status !== "REOPENED") ? query.action : null;
  const selectedAction = actionChoices.find(([key]) => key === query.action)?.[0];

  return <section className="inner-page"><div className="page-shell">
    <p className="section-kicker">Citizen service · {complaint.reference}</p>
    <div className="mt-3 flex flex-wrap items-start justify-between gap-3"><div><h1 className="page-heading">{complaint.title}</h1><p className="page-subtitle">Case Action Center</p></div><StatusBadge status={complaint.status} /></div>
    <AdminNav /><ErrorNotice error={query.error} />

    <div className="mt-7 grid gap-6 lg:grid-cols-[minmax(0,1.5fr)_minmax(280px,1fr)]">
      <div className="space-y-6">
        <article className="surface-card"><h2 className="text-xl font-bold">1. Understand the report</h2>
          <div className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><p><strong>Category:</strong> {complaint.category}</p><p><strong>Area:</strong> {complaint.area}</p><p><strong>Location:</strong> {complaint.location ?? "No additional location supplied"}</p><p><strong>Citizen:</strong> {complaint.user ? `${complaint.user.name} · ${complaint.user.email}` : "Legacy case; no linked account"}</p><p><strong>Submitted:</strong> {formatPakistanDateTime(complaint.createdAt)}</p></div>
          <p className="mt-5 whitespace-pre-wrap rounded-xl bg-slate-50 p-4 text-sm leading-7 text-slate-700">{complaint.description}</p>
          <h3 className="mt-6 font-bold">Case photos</h3><div className="mt-3"><EvidenceCards evidence={complaint.evidence} complaintId={complaint.id} admin /></div>
        </article>

        {reviewStage && <article className="surface-card"><h2 className="text-xl font-bold">2. Review this complaint</h2><p className="mt-2 text-sm text-slate-600">Check the report and choose what the citizen needs next. Give a clear reason; the citizen can see the decision.</p>
          <div className="mt-5 grid gap-3 sm:grid-cols-3">
            <ActionLink href={`${casePath}?action=verify#guided-action`} active={selectedReview === "verify"} title="Verify complaint" detail="Tasdeeq karein" />
            {["SUBMITTED", "UNDER_REVIEW"].includes(complaint.status) && <ActionLink href={`${casePath}?action=information#guided-action`} active={selectedReview === "information"} title="Request more information" detail="Mazeed maloomat" />}
            {complaint.status !== "REOPENED" && <ActionLink href={`${casePath}?action=reject#guided-action`} active={selectedReview === "reject"} title="Reject with reason" detail="Wajah batayein" />}
          </div>
          {selectedReview && <form id="guided-action" action={guidedReviewAction} className="mt-5 space-y-3 rounded-xl border border-emerald-200 bg-emerald-50 p-4"><input type="hidden" name="complaintId" value={complaint.id} /><input type="hidden" name="decision" value={selectedReview === "verify" ? "VERIFY" : selectedReview === "information" ? "REQUEST_INFO" : "REJECT"} /><label className="field-label" htmlFor="review-reason">{selectedReview === "verify" ? "What did you verify?" : selectedReview === "information" ? "What information should the citizen provide?" : "Why is this report being rejected?"}</label><textarea id="review-reason" name="reason" className="field-input min-h-28" minLength={3} maxLength={1000} required /><button type="submit" className="btn-dark cursor-pointer">{selectedReview === "verify" ? "Confirm verification" : selectedReview === "information" ? "Send information request" : "Record rejection"}</button></form>}
        </article>}

        {actionStage && <article className="surface-card"><h2 className="text-xl font-bold">2. Choose how to help</h2><p className="mt-2 text-sm text-slate-600">Pick one or more paths as needed. Continue an existing task or referral when it already covers the work.</p>
          <div className="mt-5 grid gap-3 sm:grid-cols-2">{actionChoices.map(([key, title, detail]) => <ActionLink key={key} href={`${casePath}?action=${key}#guided-action`} active={selectedAction === key} title={title} detail={detail} />)}</div>
          {selectedAction === "government" && <div id="guided-action" className="mt-5 space-y-4 rounded-xl border border-emerald-200 bg-emerald-50 p-4"><h3 className="font-bold">Department referral</h3><p className="text-sm">Creating a draft does not mean it has been sent. Record submission only after it actually happens.</p>{complaint.referrals.filter(item => item.status === "DRAFT").map(item => <form key={item.id} action={updateReferralAction} className="grid gap-3 rounded-lg bg-white p-4 sm:grid-cols-2"><input type="hidden" name="referralId" value={item.id} /><input type="hidden" name="status" value="SUBMITTED" /><p className="font-semibold sm:col-span-2">Existing draft: {item.department.name} · {item.code}</p><Field label="Actual submission method"><input name="submissionMethod" className="field-input" maxLength={120} required placeholder="Official portal, hand delivery…" /></Field><Field label="Actual submission date"><input name="submittedAt" type="date" max={new Date().toISOString().slice(0, 10)} className="field-input" required /></Field><Field label="Official reference, if provided"><input name="officialReference" className="field-input" maxLength={120} /></Field><Field label="Follow-up date"><input name="followUpAt" type="date" className="field-input" /></Field><button type="submit" className="btn-dark w-fit cursor-pointer sm:col-span-2">Record actual submission</button></form>)}<form action={createReferralDraftAction} className="grid gap-3 rounded-lg bg-white p-4 sm:grid-cols-[1fr_auto]"><input type="hidden" name="complaintId" value={complaint.id} /><Field label="Department"><select name="departmentId" className="field-input" required><option value="">Select department</option>{departments.map(item => <option key={item.id} value={item.id}>{item.name} · {item.jurisdiction}</option>)}</select></Field><button type="submit" disabled={!departments.length} className="btn-dark cursor-pointer self-end disabled:opacity-50">Prepare referral draft</button></form>{!departments.length && <Link href="/admin/departments" className="text-sm font-bold text-emerald-700 underline">Add a department first</Link>}</div>}
          {(selectedAction === "team" || selectedAction === "ngo") && <div id="guided-action" className="mt-5 rounded-xl border border-emerald-200 bg-emerald-50 p-4"><h3 className="font-bold">{selectedAction === "team" ? "Assign volunteer / team" : "Coordinate with partner NGO"}</h3>{openTasks.length > 0 && <p className="mt-2 text-sm">This case already has {openTasks.length} active task{openTasks.length === 1 ? "" : "s"}. <Link href="/admin/tasks" className="font-bold text-emerald-700 underline">Continue or reassign existing work</Link> when it covers this action.</p>}<form action={createTaskAction} className="mt-4 grid gap-3 sm:grid-cols-2"><input type="hidden" name="complaintId" value={complaint.id} />{selectedAction === "ngo" ? <input type="hidden" name="type" value="PARTNER_NGO" /> : <Field label="Work needed"><select name="type" className="field-input">{taskTypes.filter(item => item !== "PARTNER_NGO").map(item => <option key={item} value={item}>{label(item)}</option>)}</select></Field>}<Field label="Priority"><select name="priority" className="field-input">{priorities.map(item => <option key={item} value={item}>{label(item)}</option>)}</select></Field><Field label={selectedAction === "team" ? "Assign to" : "Internal coordinator (optional)"}><select name="assigneeId" className="field-input" required={selectedAction === "team"}><option value="">{selectedAction === "team" ? "Select person" : "Not assigned"}</option>{assignees.map(item => <option key={item.id} value={item.id}>{item.name} ({label(item.role)})</option>)}</select></Field>{selectedAction === "ngo" && <Field label="Partner NGO name"><input name="partnerName" className="field-input" maxLength={120} required /></Field>}<TaskDeadlineField /><div className="sm:col-span-2"><label className="field-label" htmlFor="task-instructions">What should be done?</label><textarea id="task-instructions" name="instructions" className="field-input min-h-24" minLength={10} maxLength={3000} required /></div><button type="submit" className="btn-dark w-fit cursor-pointer sm:col-span-2">Create action task</button></form></div>}
          {selectedAction === "direct" && <div id="guided-action" className="mt-5 space-y-4 rounded-xl border border-emerald-200 bg-emerald-50 p-4"><h3 className="font-bold">Record action by {brand.name}</h3>{nextComplaintStatuses(complaint.status).includes("IN_PROGRESS") ? <form action={complaintStatusAction} className="space-y-3"><input type="hidden" name="complaintId" value={complaint.id} /><input type="hidden" name="status" value="IN_PROGRESS" /><label className="field-label" htmlFor="direct-reason">What action has begun? (citizen can see this)</label><textarea id="direct-reason" name="reason" className="field-input min-h-24" minLength={3} maxLength={1000} required /><button type="submit" className="btn-dark cursor-pointer">Record progress</button></form> : <p className="text-sm">Work is already in progress. Add a photo or an internal coordination note below.</p>}<EvidenceForm complaintId={complaint.id} stage="PROGRESS" /><details className="rounded-lg bg-white p-3"><summary className="cursor-pointer font-semibold">Add internal coordination note</summary><NoteForm complaintId={complaint.id} /></details></div>}
        </article>}

        {(actionStage || complaint.status === "RESOLUTION_PROPOSED" || complaint.status === "RESOLVED") && <article className="surface-card"><h2 className="text-xl font-bold">3. Confirm the result</h2>{actionStage && <><p className="mt-2 text-sm text-slate-600">Share an after photo with the citizen before proposing a resolution. A completed task or department response does not close the complaint.</p>{!afterShared && <div className="mt-5 rounded-xl bg-amber-50 p-4"><p className="mb-4 text-sm font-semibold text-amber-900">Completion photo needed before proposing resolution.</p><EvidenceForm complaintId={complaint.id} stage="AFTER" /></div>}{afterShared && nextComplaintStatuses(complaint.status).includes("RESOLUTION_PROPOSED") && <form action={complaintStatusAction} className="mt-5 space-y-3 rounded-xl bg-emerald-50 p-4"><input type="hidden" name="complaintId" value={complaint.id} /><input type="hidden" name="status" value="RESOLUTION_PROPOSED" /><label className="field-label" htmlFor="resolution-reason">Explain what was completed</label><textarea id="resolution-reason" name="reason" className="field-input min-h-24" minLength={3} maxLength={1000} required /><button type="submit" className="btn-dark cursor-pointer">Propose resolution and request citizen review</button></form>}</>}{complaint.status === "RESOLUTION_PROPOSED" && (complaint.userId ? <p className="mt-4 text-sm">Waiting for the citizen to confirm or dispute the proposal. Their decision is available through their private <Link href={`/track?ref=${encodeURIComponent(complaint.reference)}`} className="font-bold text-emerald-700 underline">case tracking page</Link>.</p> : <form action={complaintStatusAction} className="mt-4 space-y-3"><input type="hidden" name="complaintId" value={complaint.id} /><input type="hidden" name="status" value="RESOLVED" /><p className="text-sm">This legacy case has no citizen owner. Confirm the recorded field verification and after evidence before closing.</p><label className="field-label" htmlFor="legacy-reason">Closure review</label><textarea id="legacy-reason" name="reason" className="field-input min-h-24" minLength={3} maxLength={1000} required /><button type="submit" className="btn-dark cursor-pointer">Close verified legacy case</button></form>)}{complaint.status === "RESOLVED" && <p className="mt-4 text-sm">The resolution is recorded. The citizen can reopen the case if the issue returns.</p>}</article>}
      </div>

      <aside className="space-y-6"><div className="surface-card"><h2 className="text-lg font-bold">What the citizen sees</h2><p className="mt-3 text-sm leading-6 text-slate-700">{citizenProgress(complaint.status, Boolean(complaint.userId), informationRequested)}</p><p className="mt-3 text-xs text-slate-500">Internal notes and draft referrals stay private.</p></div><div className="surface-card"><h2 className="text-lg font-bold">Action already underway</h2><div className="mt-4 space-y-3">{complaint.tasks.map(item => <div key={item.id} className="rounded-lg border border-slate-100 p-3 text-sm"><p className="font-semibold">{item.code} · {label(item.type)}</p><p>{item.assignee?.name ?? item.partnerName ?? "Unassigned"} · {label(item.status)}</p><p className="text-xs text-slate-500">Due {item.deadline.toLocaleDateString("en-PK")}</p></div>)}{complaint.referrals.map(item => <div key={item.id} className="rounded-lg border border-slate-100 p-3 text-sm"><p className="font-semibold">{item.department.name}</p><p>{item.submittedAt ? `Submitted ${item.submittedAt.toLocaleDateString("en-PK")}` : "Draft only · not sent"} · {label(item.status)}</p></div>)}{!complaint.tasks.length && !complaint.referrals.length && <p className="text-sm text-slate-500">No action recorded yet.</p>}</div></div><div className="surface-card"><h2 className="text-lg font-bold">Recent case activity</h2><div className="mt-5"><Timeline events={complaint.events.slice(0, 8)} /></div></div></aside>
    </div>

    <details className="surface-card mt-7"><summary className="cursor-pointer text-xl font-bold">Advanced Controls</summary><p className="mt-2 text-sm text-slate-600">Detailed status changes, internal coordination, public map approval and audit history.</p><div className="mt-6 grid gap-6 lg:grid-cols-2"><div className="space-y-6"><AdvancedCaseTools complaintId={complaint.id} assignees={assignees} /><div><h3 className="font-bold">Raw status control</h3>{allowed.length ? <form action={complaintStatusAction} className="mt-3 space-y-3"><input type="hidden" name="complaintId" value={complaint.id} /><Field label="Next valid status"><select name="status" className="field-input">{allowed.map(status => <option key={status} value={status}>{label(status)}</option>)}</select></Field><Field label="Reason / update"><textarea name="reason" className="field-input min-h-24" minLength={3} maxLength={1000} required /></Field><button type="submit" className="btn-dark cursor-pointer">Record status change</button></form> : <p className="mt-2 text-sm">No admin transition is available.</p>}</div><div><h3 className="font-bold">Internal note</h3><p className="text-xs text-slate-500">Hidden from citizens and public tracking.</p><NoteForm complaintId={complaint.id} /></div><PublicMapApproval complaint={complaint} /></div><div><h3 className="font-bold">Full case timeline</h3><div className="mt-4"><Timeline events={complaint.events} /></div><h3 className="mt-7 font-bold">Complaint audit log</h3><div className="mt-3 space-y-2">{audits.length ? audits.map(item => <p key={item.id} className="border-b border-slate-100 pb-2 text-xs text-slate-600">{formatPakistanDateTime(item.createdAt)} · {item.actor?.name ?? "Former team member"} · {item.action}{item.details ? ` · ${item.details}` : ""}</p>) : <p className="text-sm text-slate-500">No direct complaint audit entries.</p>}</div></div></div></details>
  </div></section>;
}

function ActionLink({ href, active, title, detail }: { href: string; active: boolean; title: string; detail: string }) {
  return <Link href={href} aria-current={active ? "step" : undefined} className={`rounded-xl border p-4 text-left transition-colors ${active ? "border-emerald-500 bg-emerald-50" : "border-slate-200 bg-white hover:border-emerald-400"}`}><span className="block font-bold">{title}</span><span className="mt-1 block text-xs text-slate-600">{detail}</span></Link>;
}
function Field({ label: fieldLabel, children }: { label: string; children: React.ReactNode }) {
  return <label className="block"><span className="field-label">{fieldLabel}</span>{children}</label>;
}
function EvidenceForm({ complaintId, stage }: { complaintId: string; stage: "PROGRESS" | "AFTER" }) {
  return <form action={uploadEvidenceAction} className="grid gap-3 sm:grid-cols-2"><input type="hidden" name="complaintId" value={complaintId} /><input type="hidden" name="stage" value={stage} /><input type="hidden" name="visibility" value={stage === "AFTER" ? "OWNER" : "INTERNAL"} /><div className="sm:col-span-2"><label className="field-label" htmlFor={`${stage}-photo`}>{stage === "AFTER" ? "Completion photo to share with citizen" : "Progress photo"} (JPEG, PNG or WebP; max 5 MB)</label><input id={`${stage}-photo`} name="file" type="file" accept="image/jpeg,image/png,image/webp" className="field-input" required /></div><Field label="Field note (optional)"><input name="note" className="field-input" maxLength={1000} /></Field><button type="submit" className="btn-dark w-fit cursor-pointer self-end">Upload {stage === "AFTER" ? "completion" : "progress"} photo</button></form>;
}
function NoteForm({ complaintId }: { complaintId: string }) {
  return <form action={caseNoteAction} className="mt-3 space-y-3"><input type="hidden" name="complaintId" value={complaintId} /><label className="field-label" htmlFor={`note-${complaintId}`}>Note for the team</label><textarea id={`note-${complaintId}`} name="note" className="field-input min-h-24" minLength={3} maxLength={2000} required /><button type="submit" className="btn-dark cursor-pointer">Save internal note</button></form>;
}
