import { createTaskAction, uploadEvidenceAction } from "@/app/actions/operations";
import { evidenceStages, label, priorities, taskTypes } from "@/lib/workflow";

export function AdvancedCaseTools({ complaintId, assignees }: { complaintId: string; assignees: { id: string; name: string; role: string }[] }) {
  return <div className="space-y-6">
    <details className="rounded-xl border border-slate-200 p-4"><summary className="cursor-pointer font-bold">Custom task</summary><p className="mt-2 text-xs text-slate-600">For additional work that an existing task does not cover.</p><form action={createTaskAction} className="mt-4 grid gap-3 sm:grid-cols-2"><input type="hidden" name="complaintId" value={complaintId} /><label className="block"><span className="field-label">Type</span><select name="type" className="field-input">{taskTypes.map(item => <option key={item} value={item}>{label(item)}</option>)}</select></label><label className="block"><span className="field-label">Priority</span><select name="priority" className="field-input">{priorities.map(item => <option key={item} value={item}>{label(item)}</option>)}</select></label><label className="block"><span className="field-label">Assignee</span><select name="assigneeId" className="field-input"><option value="">Unassigned</option>{assignees.map(item => <option key={item.id} value={item.id}>{item.name} ({label(item.role)})</option>)}</select></label><label className="block"><span className="field-label">Partner NGO, if any</span><input name="partnerName" className="field-input" maxLength={120} /></label><label className="block"><span className="field-label">Deadline</span><input name="deadline" type="datetime-local" className="field-input" required /></label><label className="block sm:col-span-2"><span className="field-label">Instructions</span><textarea name="instructions" className="field-input min-h-24" minLength={10} maxLength={3000} required /></label><button type="submit" className="btn-dark w-fit cursor-pointer sm:col-span-2">Create task</button></form></details>
    <details className="rounded-xl border border-slate-200 p-4"><summary className="cursor-pointer font-bold">Other field evidence</summary><form action={uploadEvidenceAction} className="mt-4 grid gap-3 sm:grid-cols-2"><input type="hidden" name="complaintId" value={complaintId} /><label className="block"><span className="field-label">Stage</span><select name="stage" className="field-input">{evidenceStages.map(item => <option key={item} value={item}>{label(item)}</option>)}</select></label><label className="block"><span className="field-label">Visibility</span><select name="visibility" className="field-input"><option value="INTERNAL">Internal only</option><option value="OWNER">Share with citizen</option></select></label><label className="block sm:col-span-2"><span className="field-label">Photo (JPEG, PNG, WebP; max 5 MB)</span><input name="file" type="file" accept="image/jpeg,image/png,image/webp" className="field-input" required /></label><label className="block sm:col-span-2"><span className="field-label">Field note</span><input name="note" className="field-input" maxLength={1000} /></label><button type="submit" className="btn-dark w-fit cursor-pointer sm:col-span-2">Upload photo</button></form></details>
  </div>;
}
