"use client";

import Image from "next/image";
import { useState } from "react";

export function BeforeAfter({ before, after, title }: { before: string; after: string; title: string }) {
  const [position, setPosition] = useState(50);
  return <div><div className="relative aspect-[4/3] w-full overflow-hidden rounded-2xl bg-slate-100 sm:aspect-video"><Image unoptimized src={after} alt={`After work: ${title}`} fill className="object-cover" /><div className="absolute inset-0" style={{ clipPath: `inset(0 ${100 - position}% 0 0)` }}><Image unoptimized src={before} alt={`Before work: ${title}`} fill className="object-cover" /></div><span className="absolute left-3 top-3 rounded-full bg-slate-900/85 px-3 py-1 text-xs font-bold text-white">Before</span><span className="absolute right-3 top-3 rounded-full bg-emerald-800/90 px-3 py-1 text-xs font-bold text-white">After</span><div className="pointer-events-none absolute inset-y-0 w-0.5 bg-white shadow" style={{ left: `${position}%` }} /></div><label className="mt-4 block text-sm font-semibold text-slate-700" htmlFor={`comparison-${title.replaceAll(/\W/g, "-")}`}>Compare before and after</label><input id={`comparison-${title.replaceAll(/\W/g, "-")}`} type="range" min="0" max="100" value={position} onChange={event => setPosition(Number(event.target.value))} aria-valuetext={`${position}% before photo visible`} className="mt-2 w-full accent-emerald-700" /><details className="mt-3 rounded-xl border p-3"><summary className="cursor-pointer text-sm font-bold">View photos side by side</summary><div className="mt-3 grid gap-3 sm:grid-cols-2"><div><Image unoptimized src={before} alt={`Before: ${title}`} width={650} height={450} className="h-auto w-full rounded-lg" /><p className="mt-1 text-xs font-bold">Before</p></div><div><Image unoptimized src={after} alt={`After: ${title}`} width={650} height={450} className="h-auto w-full rounded-lg" /><p className="mt-1 text-xs font-bold">After</p></div></div></details></div>;
}
