
import { brand } from "@/lib/brand";
import { requireRole } from "@/lib/auth/session";
import { prisma } from "@/lib/prisma";
import { AdminNav, ErrorNotice } from "@/components/operations";
import { saveHelpArticleAction } from "@/app/actions/help";

export const dynamic = "force-dynamic";
export default async function AdminHelpPage({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  await requireRole(["ADMIN"]);
  const [{ error }, articles, cities] = await Promise.all([searchParams, prisma.helpArticle.findMany({ orderBy: { updatedAt: "desc" } }), prisma.city.findMany({ select: { id: true, name: true, status: true }, orderBy: { name: "asc" } })]);
  return <section className="inner-page"><div className="page-shell"><p className="section-kicker">Approved guidance</p><h1 className="page-heading mt-3">Help knowledge base</h1><p className="page-subtitle">Publish only checked {brand.name} guidance. Do not add unverified department contacts or claim an official relationship. Legacy articles remain Karachi-specific until reviewed.</p><AdminNav /><ErrorNotice error={error} /><div className="surface-card mt-8"><h2 className="text-xl font-bold">New article</h2><ArticleForm cities={cities} /></div><div className="mt-6 space-y-5">{articles.map(article => <div key={article.id} className="surface-card"><p className="mb-4 text-xs font-bold text-slate-500">{article.published ? "Published" : "Draft"} · Updated {article.updatedAt.toLocaleString("en-PK")}</p><ArticleForm article={article} cities={cities} /></div>)}</div></div></section>;
}

function ArticleForm({ article, cities }: { article?: { id: string; cityId: string | null; title: string; category: string; language: string; content: string; published: boolean }; cities: { id: string; name: string; status: string }[] }) {
  return <form action={saveHelpArticleAction} className="mt-4 grid gap-4 sm:grid-cols-2">{article && <input type="hidden" name="id" value={article.id} />}<div><label className="field-label" htmlFor={`title-${article?.id ?? "new"}`}>Title</label><input id={`title-${article?.id ?? "new"}`} name="title" defaultValue={article?.title} className="field-input" minLength={5} maxLength={120} required /></div><div><label className="field-label" htmlFor={`category-${article?.id ?? "new"}`}>Category</label><input id={`category-${article?.id ?? "new"}`} name="category" defaultValue={article?.category} className="field-input" minLength={2} maxLength={60} placeholder="e.g. Reporting, support, referrals" required /></div><div><label className="field-label" htmlFor={`city-${article?.id ?? "new"}`}>City guidance</label><select id={`city-${article?.id ?? "new"}`} name="cityId" className="field-input" defaultValue={article ? article.cityId ?? "" : "karachi"}><option value="">Legacy Karachi guidance</option>{cities.map(city => <option key={city.id} value={city.id}>{city.name}{city.status !== "ACTIVE" ? " · Coming Soon" : ""}</option>)}</select></div><div><label className="field-label" htmlFor={`language-${article?.id ?? "new"}`}>Language</label><select id={`language-${article?.id ?? "new"}`} name="language" className="field-input" defaultValue={article?.language ?? "en"}><option value="en">English</option><option value="ur">Urdu</option><option value="ur-Latn">Roman Urdu</option></select></div><div><label className="field-label" htmlFor={`published-${article?.id ?? "new"}`}>Publication</label><select id={`published-${article?.id ?? "new"}`} name="published" className="field-input" defaultValue={article?.published ? "1" : "0"}><option value="0">Draft</option><option value="1">Published and approved</option></select></div><div className="sm:col-span-2"><label className="field-label" htmlFor={`content-${article?.id ?? "new"}`}>Help content</label><textarea id={`content-${article?.id ?? "new"}`} name="content" defaultValue={article?.content} className="field-input min-h-36" minLength={20} maxLength={5000} required /></div><button type="submit" className="btn-dark w-fit cursor-pointer">{article ? "Save article" : "Create article"}</button></form>;
}
