import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { BeforeAfter } from "@/components/before-after";
import { getPublishedStory } from "@/lib/completed-work-public";

export const metadata: Metadata = { title: "Verified completed work" };
export const dynamic = "force-dynamic";
const pkr = (value: number) => `PKR ${value.toLocaleString("en-PK")}`;

export default async function CompletedStoryPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const story = await getPublishedStory(id);
  if (!story) notFound();
  const timeline = [{ label: "Report submitted", date: story.submittedAt }, ...(story.verifiedAt ? [{ label: "Complaint verified", date: story.verifiedAt }] : []), { label: "Resolution confirmed", date: story.completedAt }];
  return <section className="inner-page"><div className="page-shell"><Link href="/projects" className="text-sm font-bold text-emerald-700 underline">← Our Projects</Link><p className="section-kicker mt-6">Verified Before &amp; After</p><h1 className="page-heading mt-3">{story.title}</h1><p className="page-subtitle">{story.category} · District {story.district} · {story.area}</p><div className="mt-5 flex flex-wrap gap-3 text-sm"><span className="rounded-full bg-emerald-100 px-3 py-1 font-bold text-emerald-900">Resolution confirmed</span><span className="rounded-full bg-slate-100 px-3 py-1">Completed {story.completedAt.toLocaleDateString("en-PK")}</span></div><div className="surface-card mt-7"><BeforeAfter before={`/api/projects/completed/${id}/media/before`} after={`/api/projects/completed/${id}/media/after`} title={story.title} /></div><div className="mt-6 grid gap-6 lg:grid-cols-2"><section className="surface-card"><h2 className="text-xl font-bold">Original problem</h2><p className="mt-3 whitespace-pre-wrap text-sm leading-7 text-slate-700">{story.problemSummary}</p></section><section className="surface-card"><h2 className="text-xl font-bold">Work performed</h2><p className="mt-3 whitespace-pre-wrap text-sm leading-7 text-slate-700">{story.workSummary}</p>{story.project && <p className="mt-4 text-sm">Approved partner credit: <Link href={`/projects/${story.project.id}`} className="font-bold text-emerald-700 underline">{story.project.ngoName}</Link></p>}</section></div><section className="surface-card mt-6"><h2 className="text-xl font-bold">Public case timeline</h2><ol className="mt-4 space-y-3">{timeline.map(item => <li key={item.label} className="flex flex-wrap justify-between gap-2 border-l-2 border-emerald-400 pl-4 text-sm"><span>{item.label}</span><time>{item.date.toLocaleDateString("en-PK")}</time></li>)}</ol><p className="mt-5 text-sm">Complaint reference: <Link href={story.publicMapCase ? `/map/case/${story.complaintId}` : `/track?ref=${encodeURIComponent(story.reference)}`} className="font-bold text-emerald-700 underline">{story.reference}</Link></p></section>{story.funds && <section className="surface-card mt-6"><h2 className="text-xl font-bold">Verified linked funding</h2><p className="mt-2 text-sm">{story.funds.campaignTitle}</p><p className="mt-3 text-sm">Net verified donations: {pkr(story.funds.verifiedNet)} · Paid expenses: {pkr(story.funds.spent)}</p><Link href="/funds" className="mt-3 inline-block text-sm font-bold text-emerald-700 underline">See full financial transparency</Link></section>}<p className="mt-6 text-xs text-slate-500">Only team-approved public descriptions and photos are shown. Private case notes, donor information and precise locations remain protected.</p></div></section>;
}
