import { prisma } from "@/lib/prisma";
import { requireRole } from "@/lib/auth/session";
import { saveCampaignAction } from "@/app/actions/donations";
import { AdminNav, ErrorNotice } from "@/components/operations";
import { DonationAdminNav } from "@/components/donation-admin-nav";

export const dynamic = "force-dynamic";
export default async function CampaignsPage({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  await requireRole(["ADMIN"]);
  const [{ error }, campaigns] = await Promise.all([searchParams, prisma.donationCampaign.findMany({ orderBy: { createdAt: "desc" }, include: { complaint: { select: { reference: true } } } })]);
  return <section className="inner-page"><div className="page-shell"><p className="section-kicker">Approved fundraising</p><h1 className="page-heading mt-3">Community campaigns</h1><p className="page-subtitle">Publish only documented, legitimate community projects. Linking an individual complaint requires a recorded verification event. Fundraising never changes complaint priority.</p><AdminNav /><DonationAdminNav /><ErrorNotice error={error} /><div className="surface-card mt-8"><h2 className="text-xl font-bold">Create campaign</h2><CampaignForm /></div><div className="mt-6 space-y-5">{campaigns.map(item => <div key={item.id} className="surface-card"><p className="text-xs font-bold text-emerald-700">{item.status} · {item.complaint?.reference ?? "Independent community project"}</p><CampaignForm item={item} /></div>)}</div></div></section>;
}
function CampaignForm({ item }: { item?: { id: string; slug: string; title: string; description: string; goalPkr: number | null; complaintId: string | null; verificationNote: string | null; status: string } }) {
  return <form action={saveCampaignAction} className="mt-4 grid gap-4 sm:grid-cols-2">{item && <input type="hidden" name="id" value={item.id} />}<div><label className="field-label" htmlFor={`slug-${item?.id ?? "new"}`}>URL slug</label><input id={`slug-${item?.id ?? "new"}`} name="slug" defaultValue={item?.slug} className="field-input" pattern="[a-z0-9]+(-[a-z0-9]+)*" minLength={3} maxLength={70} required /></div><div><label className="field-label" htmlFor={`title-${item?.id ?? "new"}`}>Public title</label><input id={`title-${item?.id ?? "new"}`} name="title" defaultValue={item?.title} className="field-input" minLength={5} maxLength={120} required /></div><div className="sm:col-span-2"><label className="field-label" htmlFor={`description-${item?.id ?? "new"}`}>Public project description</label><textarea id={`description-${item?.id ?? "new"}`} name="description" defaultValue={item?.description} className="field-input min-h-28" minLength={30} maxLength={3000} required /></div><div><label className="field-label" htmlFor={`goal-${item?.id ?? "new"}`}>Optional goal (PKR)</label><input id={`goal-${item?.id ?? "new"}`} name="goalPkr" type="number" min={100} max={1000000} defaultValue={item?.goalPkr ?? ""} className="field-input" /></div><div><label className="field-label" htmlFor={`complaint-${item?.id ?? "new"}`}>Verified complaint ID (optional)</label><input id={`complaint-${item?.id ?? "new"}`} name="complaintId" defaultValue={item?.complaintId ?? ""} className="field-input" /></div><div className="sm:col-span-2"><label className="field-label" htmlFor={`verification-${item?.id ?? "new"}`}>Internal legitimacy check (required to publish)</label><textarea id={`verification-${item?.id ?? "new"}`} name="verificationNote" defaultValue={item?.verificationNote ?? ""} className="field-input min-h-24" maxLength={1000} placeholder="Describe how the team verified this community project and its purpose." /></div><div><label className="field-label" htmlFor={`status-${item?.id ?? "new"}`}>Status</label><select id={`status-${item?.id ?? "new"}`} name="status" defaultValue={item?.status ?? "DRAFT"} className="field-input"><option value="DRAFT">Draft (private)</option><option value="PUBLISHED">Published and accepting support</option><option value="CLOSED">Closed to new support</option></select></div><button type="submit" className="btn-dark w-fit cursor-pointer self-end">{item ? "Save campaign" : "Create campaign"}</button></form>;
}
