
import { brand } from "@/lib/brand";
import type { Metadata } from "next";
import Link from "next/link";
import { getFinanceSnapshot } from "@/lib/finance";
import { activePublicCities, selectedPublicCity } from "@/lib/public-cities";
import { notFound } from "next/navigation";

export const metadata: Metadata = { title: "Our Funds" };
export const dynamic = "force-dynamic";
const money = (value: number) => `PKR ${value.toLocaleString("en-PK")}`;

export default async function FundsPage({ searchParams }: { searchParams: Promise<{ city?: string }> }) {
  const [{ city: slug }, cities] = await Promise.all([searchParams, activePublicCities()]);
  const city = selectedPublicCity(slug, cities);
  if (city === undefined) notFound();
  const funds = await getFinanceSnapshot(city?.id ?? undefined);
  const maxMonth = Math.max(1, ...funds.monthly.flatMap(item => [item.received, Math.abs(item.spent)]));
  return <section className="inner-page"><div className="page-shell"><p className="section-kicker">Community finance transparency</p><h1 className="page-heading mt-3">Our Funds{city ? ` · ${city.name}` : " · Nationwide"}</h1><p className="page-subtitle">Figures come from independently checked transfers and recorded paid expenses. Pending claims are excluded. Refunded transfers are shown separately and excluded from available funds. City totals include only explicitly allocated receipts, expenses and campaigns.</p><nav aria-label="Filter funds by city" className="mt-5 flex flex-wrap gap-2"><Link href="/funds" aria-current={!city ? "page" : undefined} className="rounded-full border border-emerald-200 px-4 py-2 text-sm font-bold text-emerald-900">Nationwide</Link>{cities.map(item => <Link key={item.id} href={`/funds?city=${encodeURIComponent(item.slug)}`} aria-current={city?.id === item.id ? "page" : undefined} className="rounded-full border border-emerald-200 px-4 py-2 text-sm font-bold text-emerald-900">{item.name}</Link>)}</nav>
    <div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Verified receipts, before refunds", funds.gross], ["Verified refunds", funds.refunds], ["Paid documented expenses", funds.spent], ["Available balance", funds.available]].map(([label, value]) => <div key={label} className="surface-card"><p className="text-2xl font-bold text-[#133f41]">{money(Number(value))}</p><p className="mt-2 text-sm text-slate-600">{label}</p></div>)}</div>
    <p className="mt-4 text-sm text-slate-600">Available = verified receipts − verified refunds − paid expenses. Negative balances remain visible for reconciliation. Last financial update: {funds.lastUpdate ? funds.lastUpdate.toLocaleString("en-PK") : "No verified financial activity yet"}.</p>{funds.unallocatedGeneral && <p className="mt-3 text-sm text-slate-700">Unallocated national general funds: {money(funds.unallocatedGeneral.balance)} available. Historical donations are not assigned to Karachi without a reviewed allocation.</p>}
    {funds.negativeFunds.length > 0 && <p className="mt-4 rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm text-amber-900" role="status">Reconciliation needed: {funds.negativeFunds.length} fund allocation{funds.negativeFunds.length === 1 ? " has" : "s have"} a negative balance. The recorded amounts remain visible during review.</p>}
    <div className="mt-8 grid gap-6 lg:grid-cols-2"><article className="surface-card"><h2 className="text-xl font-bold">General fund</h2><dl className="mt-4 space-y-2 text-sm"><div className="flex justify-between"><dt>Verified received</dt><dd>{money(funds.general.received)}</dd></div><div className="flex justify-between"><dt>Refunded</dt><dd>{money(funds.general.refunded)}</dd></div><div className="flex justify-between"><dt>Paid expenses</dt><dd>{money(funds.general.spent)}</dd></div><div className="flex justify-between border-t pt-3 font-bold"><dt>General balance</dt><dd>{money(funds.general.balance)}</dd></div></dl></article><article className="surface-card"><h2 className="text-xl font-bold">Approved community projects</h2>{funds.campaigns.length ? <div className="mt-4 space-y-4">{funds.campaigns.map(item => <div key={item.id} className="border-b border-slate-100 pb-4 last:border-0"><h3 className="font-bold">{item.title}</h3><p className="mt-1 text-sm text-slate-600">Received {money(item.received)} · Refunded {money(item.refunded)} · Spent {money(item.spent)}</p><p className="mt-1 text-sm font-bold">Restricted balance {money(item.balance)}{item.goalPkr ? ` · Goal ${money(item.goalPkr)}` : ""}</p></div>)}</div> : <p className="mt-4 text-sm text-slate-600">No approved community project has been published.</p>}{funds.undisclosedRestrictedBalance !== 0 && <p className="mt-3 text-xs text-slate-600">Other restricted allocations: {money(funds.undisclosedRestrictedBalance)}. Project details are withheld until approved for publication.</p>}</article></div>
    <article className="surface-card mt-6"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-bold">Monthly history</h2><Link href={city ? `/funds/report.csv?city=${encodeURIComponent(city.slug)}` : "/funds/report.csv"} className="text-sm font-bold text-emerald-700 underline">Download summary CSV</Link></div>{funds.monthly.length ? <div className="mt-5 space-y-5">{funds.monthly.slice(-12).map(item => <div key={item.month} className="grid gap-2 text-sm sm:grid-cols-[100px_1fr_1fr]"><strong>{item.month}</strong><div><span className="text-xs">Verified receipts {money(item.received)}</span><div className="mt-1 h-3 rounded bg-emerald-100"><div className="h-3 rounded bg-emerald-600" style={{ width: `${item.received / maxMonth * 100}%` }} /></div></div><div><span className="text-xs">Paid expenses {money(item.spent)}</span><div className="mt-1 h-3 rounded bg-sky-100"><div className="h-3 rounded bg-sky-600" style={{ width: `${Math.abs(item.spent) / maxMonth * 100}%` }} /></div></div>{item.refunded > 0 && <p className="text-xs text-amber-800 sm:col-start-2 sm:col-span-2">Refunds recorded: {money(item.refunded)}</p>}</div>)}</div> : <p className="mt-4 text-sm text-slate-600">No verified receipts or paid expenses have been recorded.</p>}</article>
    <article className="surface-card mt-6"><h2 className="text-xl font-bold">Published spending updates</h2>{funds.publicExpenses.length ? <div className="mt-4 divide-y divide-slate-100">{funds.publicExpenses.map(item => <div key={item.id} className="py-4"><div className="flex flex-wrap justify-between gap-2"><strong>{item.purpose}</strong><strong>{money(item.amountPkr)}</strong></div><p className="mt-1 text-xs text-slate-500">Paid {item.paidAt?.toLocaleDateString("en-PK")} · {item.campaign?.approvedAt ? item.campaign.title : "General fund"}</p><p className="mt-2 whitespace-pre-wrap text-sm text-slate-700">{item.documentation}</p></div>)}</div> : <p className="mt-4 text-sm text-slate-600">No spending summary has been approved for publication.</p>}{funds.publicCorrections.length > 0 && <div className="mt-5 border-t pt-4"><h3 className="font-bold">Approved spending corrections</h3>{funds.publicCorrections.map(item => <p key={item.id} className="mt-3 text-sm">{item.approvedAt?.toLocaleDateString("en-PK")} · {item.deltaPkr > 0 ? "+" : ""}{money(item.deltaPkr)} expense adjustment · {item.reason}</p>)}</div>}</article><p className="mt-7 text-sm text-slate-600">This is a record of {brand.name} transactions, not an audited financial statement or tax receipt. Donor identities, transfer references and private receipts are never included. <Link href="/donate" className="font-bold text-emerald-700 underline">How optional donations work</Link>.</p>
  </div></section>;
}
